::: {.content-visible when-profile="fr"}
# Découverte des cartes choroplèthes

L'exercice précédent nous a permis de créer une carte par aplat de couleur. Ceci nous amène naturellement vers la carte choroplèthe, où l'aplat de couleur vise à représenter une information socioéconomique.

Nous allons utiliser les données de population présentes dans les données récupérées par le biais de `cartiflette`[^poplegales]. Nous allons nous amuser à créer la carte choroplèthe en lui donnant le style _vintage_ des premières cartes de Dupin (1826).

[^poplegales]: _Stricto sensu_, il faudrait vérifier que ces colonnes correspondent bien aux populations légales définies par l'Insee. Cette variable est fournie nativement par l'IGN dans ses fonds de carte. Nous laissons les lecteurs intéressés faire ce travail, qui permet de réviser les compétences `Pandas`.
:::


::: {.content-visible when-profile="en"}
# Introduction to choropleth maps

The previous exercise allowed us to create a solid color map. This naturally leads us to choropleth maps, where color shading is used to represent socioeconomic information.

We will use population data available from the datasets retrieved via `cartiflette`[^poplegales]. As an exercise, we will create a choropleth map styled in a _vintage_ look, reminiscent of the early maps of Dupin (1826).

[^poplegales]: _Stricto sensu_, we should verify that these columns accurately correspond to the official population counts defined by Insee. This variable is natively provided by IGN in its basemap data. We leave this verification to interested readers, as it offers a good opportunity to practice `Pandas` skills.
:::
