


::: {.content-visible when-profile="fr"}
Comme on peut le voir sur la carte (@fig-landes), le département des Landes est très forestier. Ceci est logique puisque les deux tiers du département sont couverts, ce qu'on peut vérifier avec le calcul suivant[^landes-epsg] :

[^landes-epsg]: Ce calcul est possible car les deux bases sont en projection Lambert 93 pour lequel les opérations géométriques (dont les calculs de surface) sont autorisés.
:::

::: {.content-visible when-profile="en"}
As seen on the map (@fig-landes), the Landes department is heavily forested. This makes sense since two-thirds of the department are covered, which can be verified with the following calculation[^landes-epsg-en]:

[^landes-epsg]: This calculation is possible because both datasets are in the Lambert 93 projection, which allows for geometric operations (including surface area calculations).

:::


```{python}
#| echo: true
f"Part du couvert forestier dans les Landes: {float(foret.area.sum()/landes.area):.0%}"
```



```{python}
#| fig-cap: "Couvert forestier des Landes"
#| label: fig-landes
# Version plotnine
from plotnine import *

map = (
  ggplot(foret) +
  geom_map(fill = "forestgreen", size = 0) +
  geom_map(data = landes, color = "black", size = 1, fill = None) +
  theme_void()
)

map
```

```{python}
#| output: false
# Version matplotlib
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(10, 10))
foret.plot(ax=ax, color="forestgreen", edgecolor=None)
landes.plot(ax=ax, edgecolor="black", linewidth=1, facecolor="none")
ax.set_axis_off()
plt.show()
```

::: {.content-visible when-profile="fr"}
Ici, la carte est assez claire et donne un message relativement lisible. Bien sûr, on ne dispose pas de détails qui pourraient intéresser les curieux (par exemple, quelles localités sont particulièrement couvertes), mais on dispose d'une vision synthétique du phénomène étudié.
:::

::: {.content-visible when-profile="en"}
Here, the map is quite clear and conveys a relatively readable message. Of course, it does not provide details that might interest curious viewers (e.g., which specific localities are particularly forested), but it does offer a synthetic view of the studied phenomenon.
:::