:::: {.content-visible when-profile="fr"}

::: {.callout-tip}
## Exercice 4: une première carte de population

L'objectif de cet exercice va être d'enrichir les informations présentées sur la carte des départements.

1. Représenter rapidement la carte des départements en colorant en fonction de la variable `POPULATION`.  

   Cette carte présente plusieurs problèmes :  
   * Si vous connaissez la géographie française, vous devriez noter une forme anormale, comme si l'axe est-ouest avait été agrandi par excès. C'est parce qu'il faut reprojeter la carte en Lambert 93.  
   * Elle est peu lisible à cause de plusieurs facteurs : gradient continu, distribution non normale de la variable, légende perfectible, etc.  

   Les prochaines questions visent à améliorer ceci progressivement.

2. Refaire cette carte dans la projection Lambert 93.  
3. Discrétiser la variable `POPULATION` en utilisant 4 classes par le biais d'une discrétisation par quantile. Refaire la carte.  
4. Diviser votre population par la taille de chaque département (en km²) en créant une variable à partir de `.area.div(1e6)`[^note-mesure].  
5. Choisir une palette de couleur _vintage_ type échelle de gris.  

[^note-mesure]: Le Lambert 93 donne une aire en mètres carrés. Pour la transformer en km², il faut faire `div(1e6)`.
:::

::::

:::: {.content-visible when-profile="en"}

::: {.callout-tip}
## Exercise 4: A First Population Map

The goal of this exercise is to enhance the information presented on the departmental map.

1. Quickly generate a map of the departments, coloring them according to the `POPULATION` variable.  

   This map presents several issues:  
   * If you are familiar with French geography, you should notice an unusual shape, as if the east-west axis were excessively stretched. This happens because the map needs to be reprojected into Lambert 93.  
   * It is difficult to read due to several factors: continuous gradient, non-normal distribution of the variable, suboptimal legend, etc.  

   The next questions aim to improve this step by step.

2. Recreate this map using the Lambert 93 projection.  
3. Discretize the `POPULATION` variable into 4 classes using quantile-based discretization, then recreate the map.  
4. Normalize the population by the area of each department (in km²) by creating a new variable using `.area.div(1e6)`[^note-mesure-en].  
5. Choose a _vintage_ grayscale color palette.  

[^note-mesure-en]: Lambert 93 provides area in square meters. To convert it to km², use `div(1e6)`.
:::

::::
