::: {.content-visible when-profile="fr"}
La localisation des stations de Vélib est disponible sur le portail _open data_ de la ville de Paris sous la forme d'un fichier `GeoJSON`:
:::

::: {.content-visible when-profile="en"}
Velib station location dataset is available from  Paris opendata portal as a `GeoJSON` file:
:::

```{python}
#| echo: true
import geopandas as gpd

velib_data = "https://opendata.paris.fr/explore/dataset/velib-emplacement-des-stations/download/?format=geojson&timezone=Europe/Berlin&lang=fr"
stations = gpd.read_file(velib_data)

stations.head(2)
```

::: {.content-visible when-profile="fr"}
Les limites administratives de la zone d'intérêt seront également utiles à l'analyse des données. Voici un code pour les récupérer.
:::

::: {.content-visible when-profile="en"}
Administrative borders are going to be useful. Here is a snippet to retrieve them:
:::

```{python}
#| echo: true
from cartiflette import carti_download

# 1. Fonds communaux
contours_villes_arrt = carti_download(
    values = ["75", "92", "93", "94"],
    crs = 4326,
    borders="COMMUNE_ARRONDISSEMENT",
    filter_by="DEPARTEMENT",
    source="EXPRESS-COG-CARTO-TERRITOIRE",
    year=2022)

# 2. Départements 
departements = contours_villes_arrt.dissolve("INSEE_DEP")
```



:::: {.content-visible when-profile="fr"}

::: {.callout-tip}
## Exercice 5: une carte de localisation infra-communale

1. Représenter les localisations des stations avec la méthode `plot`. Êtes-vous en mesure de déterminer où elles se trouvent ?
2. Pour contextualiser, ajouter des limites administratives à la carte. 
3. Utiliser la fonctionnalité `MarkerCluster` de `Folium` pour créer une carte interactive.
:::

::::


:::: {.content-visible when-profile="en"}

::: {.callout-tip}
## Exercise 5: a sub-municipal location map

1. Show the station locations using the `plot` method. Can you determine where they are?
2. To contextualize, add administrative boundaries to the map. 
3. Use the `MarkerCluster` feature in `Folium` to create an interactive map.
:::

::::