::: {.content-visible when-profile="fr"}
# Représenter des données : un premier exemple avec une carte de couverture forestière

Pour cette partie, nous allons faire une carte du couvert forestier landais à partir de la BD Forêt produite par l'IGN. L'objectif n'est plus seulement de placer des limites du territoire d'intérêt mais de représenter de l'information sur celui-ci à partir des données présentes dans un _GeoDataFrame_.

La BD Forêt étant un peu volumineuse dans le format _shapefile_, nous proposons de la récupérer dans un format plus compressé : le _geopackage_.
:::

::: {.content-visible when-profile="en"}
# Representing data: A First Example with a Forest Cover Map

In this section, we will create a map of the Landes forest cover using the BD Forêt dataset produced by IGN. The goal is no longer just to display the boundaries of the area of interest but to represent information about it using data from a _GeoDataFrame_.

Since BD Forêt is somewhat large in _shapefile_ format, we suggest retrieving it in a more compressed format: _geopackage_.
:::

```{python}
#| echo: true
foret = gpd.read_file(
  "https://minio.lab.sspcloud.fr/projet-formation/diffusion/r-geographie/landes.gpkg"
)
```

::: {.content-visible when-profile="fr"}
Nous allons aussi créer un masque pour les contours du département: 
:::

::: {.content-visible when-profile="en"}
We also need a mask for administrative area 
:::

```{python}
#| echo: true
landes = (
  departements
  .loc[departements["INSEE_DEP"] == "40"].to_crs(2154)
)
```
