::: {.exercise}
## Exercice 4: Calculer l'empreinte carbone par habitant

En premier lieu, on va calculer l'empreinte carbone de chaque commune. 


1. Créer une variable `emissions` qui correspond aux émissions totales d'une commune

2. Faire une jointure à gauche entre les données d'émissions et les données de cadrage[^notebiais].

3. Calculer l'empreinte carbone (émissions totales / population). 

A ce stade nous pourrions avoir envie d'aller vers la modélisation pour essayer d'expliquer
les déterminants de l'empreinte carbone à partir de variables communales. 
Une approche inférentielle nécessite néanmoins pour être pertinente de
vérifier en amont des statistiques descriptives.

4. Sortir un histogramme en niveau puis en log de l'empreinte carbone communale.

Avec une meilleure compréhension de nos données, nous nous rapprochons
de la statistique inférentielle. Néanmoins, nous avons jusqu'à présent
construit des statistiques univariées mais n'avons pas cherché à comprendre
les résultats en regardant le lien avec d'autres variables. 
Cela nous amène vers la statistique bivariée, notamment l'analyse des corrélations. 
Ce travail est important puisque toute modélisation ultérieure consistera à 
raffiner l'analyse des corrélations pour tenir compte des corrélations croisées
entre multiples facteurs. On propose ici de faire cette analyse
de manière minimale. 


5. Regarder la corrélation entre les variables de cadrage et l'empreinte carbone. Certaines variables semblent-elles pouvoir potentiellement influer sur l'empreinte carbone ?

:::

[^notebiais]: Idéalement, il serait nécessaire de s'assurer que cette jointure n'introduit
pas de biais. En effet, comme nos années de référence ne sont pas forcément identiques,
il peut y avoir un _mismatch_ entre nos deux sources. Le TP étant déjà long, nous n'allons pas dans cette voie.
Les lecteurs intéressés pourront effectuer une telle analyse en exercice supplémentaire.