::: {.content-visible when-profile="fr"}

:::: {.exercise}
## Exercice 1 : agrégations par groupe

1. Calculer les émissions totales du secteur "Résidentiel" par département et rapporter la valeur au département le plus polluant dans le domaine. En tirer des intutitions sur la réalité que cette statistique reflète.

2. Calculer, pour chaque département, les émissions totales de chaque secteur. Pour chaque département, calculer la proportion des émissions totales venant de chaque secteur.  

<details>
<summary>
Indice pour cette question
</summary>

* _"Grouper par"_ = `groupby`
* _"émissions totales"_ = `agg({*** : "sum"})`
</details>

::::

:::

::: {.content-visible when-profile="en"}

:::: {.exercise}
## Exercise 1: Group Aggregations

1. Calculate the total emissions of the "Residential" sector by department and compare the value to the most polluting department in this sector. Draw insights from the reality that this statistic reflects.

2. Calculate the total emissions for each sector in each department. For each department, calculate the proportion of total emissions coming from each sector.  

<details>
<summary>
Hint for this question
</summary>

* _"Group by"_ = `groupby`
* _"Total emissions"_ = `agg({*** : "sum"})`
</details>

::::

:::