```{python}
#| echo: true
#| output: false
import duckdb
coiffeurs = duckdb.sql("""
  SELECT
    siren, siret, dateDebut, enseigne1Etablissement, activitePrincipaleEtablissement, denominationUsuelleEtablissement
  FROM
    read_parquet('https://minio.lab.sspcloud.fr/lgaliana/data/sirene2024.parquet')
  WHERE
    activitePrincipaleEtablissement == '96.02A'
    AND
    denominationUsuelleEtablissement IS NOT NULL
""")
coiffeurs = coiffeurs.df() #<1>
```
1. Convert the DuckDB dataframe to a Pandas DataFrame.

```{python}
#| echo: true
coiffeurs.head(3)
```

::: {.exercise}
## Optional Exercise: Punny Hairdressers

In this exercise, we will consider only the variable `denominationUsuelleEtablissement`.

1. In this dataset, `[ND]` is a code for missing value. Since `Python` has no reason to know this a priori and therefore didn't interpret these values as missing, use the `replace` method to replace `[ND]` with an empty text field. Also, recode missing values as an empty text field to avoid future errors related to the inability to apply certain text methods to missing values.
2. Search for all occurrences where the term `tif` appears, paying attention to the capitalization of the variable. Look at some observations.
3. Using [this example](https://stackoverflow.com/a/23996414/9197726), normalize the names of the salons by removing special characters and count the most frequent puns.

:::
