::: {.content-visible when-profile="fr"}
:::: {.exercise}
## Exercice 2: Restructurer les données : wide to long

1. Créer une copie des données de l'`ADEME` en faisant `df_wide = emissions_wide.copy()`

2. Restructurer les données au format *long* pour avoir des données d'émissions par secteur en gardant comme niveau d'analyse la commune (attention aux autres variables identifiantes).

3. Faire la somme par secteur et représenter graphiquement

4. Garder, pour chaque département, le secteur le plus polluant

::::
:::

::: {.content-visible when-profile="en"}
:::: {.exercise}
## Exercice 2: Restructuring Data: Wide to Long

1. Create a copy of the ADEME data by doing `df_wide = emissions.copy()`

2. Restructure the data into the *long* format to have emission data by sector while keeping the commune as the level of analysis (pay attention to other identifying variables).

3. Sum the emissions by sector and represent it graphically.

4. For each department, identify the most polluting sector.

::::
:::
