::: {.content-visible when-profile="fr"}
A la question 1, le résultat obtenu devrait être le suivant:
:::

::: {.content-visible when-profile="en"}
In question 1, the result should be as follows:
:::

```{python}
# Question 1
emissions_residentielles = (
    emissions
    .groupby("dep")
    .agg({"Résidentiel" : "sum"})
    .reset_index()
    .sort_values("Résidentiel", ascending = False)
)
emissions_residentielles["Résidentiel (% valeur max)"] = emissions_residentielles["Résidentiel"]/emissions_residentielles["Résidentiel"].max()
emissions_residentielles.head(5)
```

::: {.content-visible when-profile="fr"}
Ce classement reflète peut-être plus la démographie que le processus qu'on désire mesurer. Sans l'ajout d'une information annexe sur la population de chaque département pour contrôler ce facteur, on peut difficilement savoir s'il y a une différence structurelle de comportement entre les habitants du Nord (département 59) et ceux de la Moselle (département 57). 
:::

::: {.content-visible when-profile="en"}
This ranking may reflect demographics rather than the process we wish to measure. Without the addition of information on the population of each département to control for this factor, it is difficult to know whether there is a structural difference in behavior between the inhabitants of Nord (département 59) and Moselle (département 57). 
:::



```{python}
# Question 2
emissions_par_departement = (
    emissions.groupby('dep').sum(numeric_only=True)
)
emissions_par_departement['total'] = emissions_par_departement.sum(axis = 1)
emissions_par_departement["Part " + secteurs] = (
    emissions_par_departement
    .loc[:, secteurs]
    .div(emissions_par_departement['total'], axis = 0)
    .mul(100)
)
```

::: {.content-visible when-profile="fr"}
A l'issue de la question 2, prenons la part des émissions de l'agriculture et du secteur tertiaire dans les émissions départementales:
:::

::: {.content-visible when-profile="en"}
At the end of question 2, let's take the share of emissions from agriculture and the tertiary sector in departmental emissions: 
:::



```{python}
emissions_par_departement.sort_values("Part Agriculture", ascending = False).head(5)
```

```{python}
emissions_par_departement.sort_values("Part Tertiaire", ascending = False).head(5)
```
