# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


main:
  - name: Home
    url: course/
    weight: 11
  - name: Introduction
    url: /course/getting-started
    weight: 20
  - name: Manipuler des données
    url: /course/manipulation
    weight: 30
  - name: Visualiser des données
    url: /course/visualisation
    weight: 40
  - name: Modéliser
    url: /course/modelisation
    weight: 50
  - name: NLP
    url: /course/NLP
    weight: 60
  - name: Approfondissements
    url: /course/modern-ds
    weight: 70
  - name: Git
    url: /course/git
    weight: 80
  - name: Annexes
    url: /course/annexes
    weight: 90
    identifier: plus
  - name: Références
    url: /course/annexes/references/_index.md
    weight: 91
    parent: plus
  - name: Evaluation
    url: /course/annexes/evaluation/_index.md
    weight: 99
    parent: plus
  - name: Github
    url: 'https://github.com/linogaliana/python-datascientist'
    weight: 10



#main:
#  - name: Home
#    url: '/'
#    weight: 10
#  - name: Courses
#    weight: 20
#    identifier: courses
#  - name: Data science
#    PageRef: course/data-science/_index.md
#    weight: 10
#    parent: courses
#  - name: Robotics
#    PageRef: course/robotics/_index.md
#    weight: 20
#    parent: courses
#  - name: Blog
#    PageRef: post/_index.md
#    weight: 30
#  - name: Contact
#    PageRef: contact/index.md
#    weight: 60
