repos:

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.4
    hooks:
    # Run the linter.
    -   id: ruff
        name: lint with ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]

    -   id: ruff
        name: sort imports with ruff
        args: [--select, I, --fix]

    # Run the formatter.
    -   id: ruff-format
        name: format with ruff
        types_or: [ python, pyi, jupyter ]

-   repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
    -   id: nbstripout

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.24
    hooks:
      - id: uv-export

