project:
  type: website
  output-dir: "./_site/en"
  render:
    - index.qmd
    # English content
    - content/getting-started/index.qmd
    - content/getting-started/01_environment.qmd
    - content/getting-started/02_data_analysis.qmd
    - content/getting-started/03_revisions.qmd
    - content/manipulation/01_numpy.qmd
    - content/manipulation/02_pandas_intro.qmd
    - content/manipulation/02_pandas_suite.qmd
    - content/manipulation/03_geopandas_intro.qmd
    - content/manipulation/04a_webscraping_TP.qmd
    - content/manipulation/04c_API_TP.qmd
    - content/manipulation/04b_regex_TP.qmd


website:
  title: "Python for data science"
  page-footer:
    left: |
      Python pour la _data science_, Lino Galiana.<br>
      Licence {{< fa brands creative-commons >}}<br>
      Code source disponible sur [`Github`](https://github.com/linogaliana/python-datascientist)
    right: |
      Site construit avec {{< fa brands python >}} et [`Quarto`](https://quarto.org/)<br>
      Inspiration pour la mise en forme du site [ici](https://www.andreashandel.com)<br>
      [Code source disponible sur {{< fa brands github >}} `GitHub`](https://github.com/linogaliana/python-datascientist)
  body-header: |
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <a href="#" onclick="this.href = location.href.replace('/en/', '/');" class="button-cta">
          <button class="btn"><i class="fa fa-language"></i> Passer à la version française 🇫🇷</button>
      </a>
  sidebar: 
    - id: introduction
      title: "Introduction"
      #collapse-level: 2
      contents:
        - href: content/getting-started/index.qmd
          text: "Introduction"
        - content/getting-started/01_environment.qmd
        - content/getting-started/02_data_analysis.qmd
        - content/getting-started/03_revisions.qmd
    - id: manipulation 
      title: "Wrangle"
      #collapse-level: 2
      contents:
        - href: content/manipulation/index.qmd
          text: "Introduction"
        - content/manipulation/01_numpy.qmd
        - content/manipulation/02_pandas_intro.qmd
        - content/manipulation/02_pandas_suite.qmd
        - content/manipulation/03_geopandas_intro.qmd
        - content/manipulation/04a_webscraping_TP.qmd
        - content/manipulation/04c_API_TP.qmd
        - content/manipulation/04b_regex_TP.qmd
    - id: communication
      title: "Communicate"
      #collapse-level: 2
      contents:
        - href: content/visualisation/index.qmd
          text: "Introduction"
        - content/visualisation/matplotlib.qmd
        - content/visualisation/maps.qmd
    - id: modelisation
      title: "Model"
      #collapse-level: 2
      contents:
        - href: content/modelisation/index.qmd
          text: "Introduction"
        - content/modelisation/0_preprocessing.qmd
        - content/modelisation/1_modelevaluation.qmd
        - content/modelisation/2_SVM.qmd
        - content/modelisation/3_regression.qmd
        - content/modelisation/4_featureselection.qmd
        - content/modelisation/5_clustering.qmd
        - content/modelisation/6_pipeline.qmd
        - content/modelisation/7_mlapi.qmd
    - id: NLP
      title: "NLP"
      #collapse-level: 2
      contents:
        - href: content/NLP/index.qmd
          text: "Introduction"
        - content/NLP/01_intro.qmd
        - content/NLP/02_exoclean.qmd
        - content/NLP/03_lda.qmd
        - content/NLP/04_word2vec.qmd
        - content/NLP/05_exo_supp.qmd
    - id: modern
      title: "In-depth"
      #collapse-level: 2
      contents:
        - href: content/modern-ds/index.qmd
          text: "Introduction"
        - content/modern-ds/continuous_integration.qmd
        - content/modern-ds/s3.qmd
        - content/modern-ds/elastic_approfondissement.qmd
        - content/modern-ds/elastic_intro.qmd
    - id: git
      title: "Git"
      #collapse-level: 2
      contents:
        - href: content/git/index.qmd
          text: "Introduction"
        - content/git/introgit.qmd
        - content/git/exogit.qmd
    - id: appendix
      title: "Annexes"
      #collapse-level: 2
      contents:
        - content/annexes/evaluation.qmd
        - content/annexes/corrections.qmd
        - href: https://linogaliana.github.io/python-datascientist-slides/#/title-slide
          text: "Slides de présentation"

citation:
  title: "Python pour la data science"
  author: Lino Galiana
  type: book
  doi: "10.5281/zenodo.8229676"
  url: https://pythonds.linogaliana.fr/
  issued: 2023


lang: en
