:::: {.content-visible when-profile="fr"}

### S'authentifier à `Github` avec un jeton: principe
[👉️ __Authentification__: processus permettant à un système informatique de s'assurer de l'identité désirant effectuer une action.]{.aside}

`Git` est un système décentralisé de contrôle de version :
les codes sont modifiés par chaque personne sur son poste de travail,
puis sont mis en conformité avec la version collective disponible
sur le dépôt distant au moment où le contributeur le décide.

Il est donc nécessaire que la forge connaisse l’identité de chacun des
contributeurs, afin de déterminer qui est l’auteur d’une modification apportée
aux codes stockés dans le dépôt distant.
Pour que `Github` reconnaisse un utilisateur proposant des modifications,
il est nécessaire de s’authentifier (un dépôt distant, même public, ne peut pas être modifié par n’importe qui). L’authentification consiste ainsi à fournir un élément que seul vous et la forge êtes censés connaître : un mot de passe, une clé compliquée, un jeton d’accès...

Plus précisément, il existe deux modalités pour faire connaître son identité à `Github` :

* une __authentification HTTPS__ (décrite ici) : l’authentification se fait avec un login et un mot de passe ou avec un _token_ (un mot de passe compliqué généré automatiquement par `Github` et connu exclusivement du détenteur du compte `Github`)  ;
* une __authentification SSH__ : l’authentification se fait par une clé cryptée disponible sur le poste de travail et que `GitHub` ou `GitLab` connaît. Une fois configurée, cette méthode ne nécessite plus de faire connaître son identité : l’empreinte digitale que constitue la clé suffit à reconnaître un utilisateur. Ce n'est pas la méthode que nous appliquerons ici[^ssh-utilitr].

[^ssh-utilitr]: La [documentation collaborative `utilitR`](https://www.book.utilitr.org/03_fiches_thematiques/fiche_configurer_git.html#interaction-avec-un-d%C3%A9p%C3%B4t-distant-principe) présente les raisons pour lesquelles il convient de favoriser
la méthode HTTPS sur la méthode SSH. 

::: {.callout-note}
## Note sur la double authentification
[👉️ __Double authentification__ ou __authentification à deux facteurs__ (2FA): pratique de sécurité consistant à autoriser une authentification seulement après avoir présenté deux preuves d'identité distinctes à un mécanisme d'authentification. Par exemple, sur une application bancaire, fournir un numéro client et un code envoyé par SMS]{.aside}


Depuis Août 2021, `Github` n'autorise plus l'authentification par mot de passe
lorsqu'on interagit (`pull`/`push`) avec un dépôt distant
([raisons ici](https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/)).
Il est nécessaire d'utiliser un *token* (jeton d'accès) qui présente l'avantage
d'être révoquable (on peut à tout moment supprimer un jeton si, par exemple,
on suspecte qu'il a été diffusé par erreur) et à droits limités 
(le jeton permet certaines opérations standards mais
n'autorise pas certaines opérations déterminantes comme la suppression
d'un dépôt).

GitHub commencera progressivement à exiger que tous les utilisateurs de GitHub activent une ou plusieurs formes d'authentification à deux facteurs (2FA). Pour plus d’informations sur le déploiement de l’inscription 2FA, consultez [cet article de blog](https://github.blog/2023-03-09-raising-the-bar-for-software-security-github-2fa-begins-march-13/). Concrètement, cela signifie que vous devrez au choix :

- Renseigner votre numéro de portable pour valider certaines connexions grâce à un code que vous recevrez par sms ;
- Installer une application d'authentification (Ex : Microsoft Authenticator) installée sur votre téléphone qui génèrera un QR code que vous pourrez scanner depuis github, ce qui ne nécessite pas que vous ayez à fournir votre numéro de téléphone
- Utiliser une clef USB de sécurité 

Pour choisir entre ces différentes options, vous pouvez vous rendre sur *Settings > Password and authentication > Enable two-factor authentication*.

:::

### Créer un jeton

[👉️ __L’authentification par jeton__ (_token authentication_) est une forme d’authentification qui permet à un utilisateur d’accéder à un service en ligne, une application, ou un site web sans qu’il n’ait à ressaisir ses identifiants. Les jetons d’authentification fonctionnent à la manière d’un ticket d’entrée à validité limitée : ils accordent un accès en continu pendant leur durée de validité. Dès que l’utilisateur se déconnecte ou quitte l’application, le jeton est invalidé.]{.aside}


La [documentation officielle](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) comporte un certain nombre de captures d'écran expliquant
comment procéder. En gardant cette documentation ouverte en cas de doute, et les instructions du prochain exercice, nous allons pouvoir créer un jeton d'authentification. 

::: {.callout-tip}
## Exercice 2 : Créer un _token_

Suivre la
[documentation officielle](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) en ne donnant que les droits `repo` au jeton[^droits].

[^droits]: Comme vous pouvez le voir, il y a de nombreux niveaux de droits différents. Votre mot de passe a en fait tout ces droits, ce qui illustre bien le pouvoir dangereux de celui-ci s'il est découvert, que ce soit du fait d'une révélation par erreur ou d'un _hacking_ de celui-ci par quelqu'un malveillant. L'utilisation de _token_ sécurise énormément votre dépôt puisqu'il ne peut pas être supprimé si le _token_ a des droits limités. De plus, si la branche principale est protégée, ce qui est le comportement par défaut de `Github`, il ne sera pas possible sans mot de passe de détruire l'historique du dépôt. 

Pour résumer les étapes devraient être les suivantes :

*Settings (account) > Developers Settings > Personal Access Token > Tokens (classic) > Generate a new token (classic) > "MyToken" > Expiration "90 days" > cocher juste "repo" > Generate token > Le copier*

__⚠️ Gardez la page ouverte__, le _token_ n'apparaît qu'une fois et nous n'avons pas encore fait l'effort de le stocker à un endroit pérenne. Cela sera l'objet du prochain exercice. Néanmoins pas d'inquiétude si vous avez perdu le _token_ avant de pouvoir le sauvegarder, vous pouvez en regénérer un nouveau en suivant à nouveau la procédure ci-dessus.

:::

Nous avons créé un _token_ et comme cela est indiqué sur la page de `Github` ou dans les consignes de l'exercice, celui-ci n'est pas pérenne. Il va donc falloir trouver un moyen de conserver celui-ci quelque part. Nous allons proposer plusieurs solutions pour cela. Ecrire celui-ci dans un fichier texte créé avec le bloc note ne fait pas parti de ces solutions, au contraire c'est une très mauvaise pratique. 

::: {.callout-important}

Il est important de ne jamais stocker un _token_, et encore moins son mot de passe, dans un projet.
Il est possible de stocker un mot de passe ou *token* de manière sécurisée et durable
avec le *credential helper* de `Git`. Celui-ci est présenté par la suite.

S'il n'est pas possible d'utiliser le *credential helper* de `Git`, un mot de passe 
ou _token_ peut être stocké de manière sécurisé dans
un système de gestion de mot de passe comme [Keepass](https://keepass.fr/).

Ne jamais stocker un jeton `Github`, ou pire un mot de passe, dans un fichier
texte non crypté. Les logiciels de gestion de mot de passe
(comme [Keepass](https://keepass.fr/), recommandé par l'Anssi)
sont simples
d'usage et permettent de ne conserver sur l'ordinateur qu'une version
hashée du mot de passe qui ne peut être décryptée qu'avec un mot de passe
connu de vous seuls. 

:::



::: {.callout-tip}
## Exercice 3: stocker son jeton (pour les utilisateurs du `SSPCloud`)

Le `SSPCloud` propose un service de stockage d'un jeton qui peut ensuite servir facilement pour s'authentifier sur `Github` quand on utilise `VSCode` ou `Jupyter`. 

* Copier le jeton qui est affiché sur la page de `Github` qui a été ouverte précédemment. Ne faites pas la sélection des lettres à la main, utilisez le bouton dédié au copier-coller ({{< fa solid clipboard >}})
* Cliquer sur la section ["Mon Compte"](https://datalab.sspcloud.fr/account/) du `SSPCloud`. Aller dans l'onglet `Git` et coller la valeur précédemment copiée. 

On peut s'arrêter à ce stade, nous utiliserons ce jeton lors du prochain exercice. 

:::

::: {.callout-tip}
## Exercice 3bis: stocker son jeton (pour les personnes n'ayant pas l'accès au `SSPCloud`)

La solution recommandée est de stocker son jeton dans un un gestionnaire de mot de passe comme 
[Keepass](https://keepass.fr/) (recommandé par l'Anssi). Il s'agit d'un logiciel qui stocke, de manière chiffrée, les mots de passe qui y sont conservés selon la logique du coffre fort numérique. 

Au-delà de l'intérêt pour stocker un jeton Github pour ce cours, ces logiciels sont très pratiques au quotidien et sécurisent l'accès à des services numériques sensibles. Ils comportent aussi des générateurs de mot de passe forts qui permettent de réduire les risques d'usurpation numérique en rendant quasi-impossible des techniques comme [l'attaque par force brute](https://fr.wikipedia.org/wiki/Attaque_par_force_brute).

:::

::::

:::: {.content-visible when-profile="en"}

### Authenticating to `Github` with a token: principle
[👉️ __Authentication__: process allowing a computer system to make sure of the identity of whoever wants to perform an action.]{.aside}

`Git` is a decentralised version control system:
code is modified by each person on their own workstation,
then brought into line with the collective version available
on the remote repository whenever the contributor decides.

The forge therefore needs to know the identity of each
contributor, in order to determine who is the author of a change made
to the code stored in the remote repository.
For `Github` to recognise a user who proposes changes,
they must authenticate (a remote repository, even a public one, cannot be modified by just anyone). Authentication thus consists in providing something that only you and the forge are supposed to know: a password, a complicated key, an access token...

More precisely, there are two ways to make your identity known to `Github`:

* an __HTTPS authentication__ (described here): authentication is done with a login and password or with a _token_ (a complicated password automatically generated by `Github` and known only to the holder of the `Github` account);
* an __SSH authentication__: authentication is done with an encrypted key available on the workstation and known to `GitHub` or `GitLab`. Once configured, this method no longer requires you to state your identity: the fingerprint that the key constitutes is enough to recognise a user. This is not the method we will apply here[^ssh-utilitr-en].

[^ssh-utilitr-en]: The [collaborative `utilitR` documentation](https://www.book.utilitr.org/03_fiches_thematiques/fiche_configurer_git.html#interaction-avec-un-d%C3%A9p%C3%B4t-distant-principe) (in French) explains why the HTTPS method should be preferred over the SSH method.

::: {.callout-note}
## A note on two-factor authentication
[👉️ __Two-factor authentication__ (2FA): security practice that authorises authentication only after two distinct proofs of identity have been presented to an authentication mechanism. For instance, in a banking app, providing a customer number and a code sent by SMS]{.aside}


Since August 2021, `Github` no longer allows password authentication
when interacting (`pull`/`push`) with a remote repository
([reasons here](https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/)).
You must use a *token* (access token), which has the advantage
of being revocable (you can delete a token at any time if, for example,
you suspect it was leaked by mistake) and of having limited rights
(the token allows certain standard operations but
does not allow certain critical operations such as deleting
a repository).

GitHub will progressively require all GitHub users to enable one or more forms of two-factor authentication (2FA). For more information on the 2FA rollout, see [this blog post](https://github.blog/2023-03-09-raising-the-bar-for-software-security-github-2fa-begins-march-13/). In practice, this means you will have to choose between:

- Providing your mobile phone number to validate some logins with a code you will receive by SMS;
- Installing an authentication app on your phone (e.g. Microsoft Authenticator) that will generate a QR code you can scan from GitHub, which does not require you to provide your phone number
- Using a USB security key

To choose between these options, go to *Settings > Password and authentication > Enable two-factor authentication*.

:::

### Creating a token

[👉️ __Token authentication__ is a form of authentication that allows a user to access an online service, an application, or a website without having to enter their credentials again. Authentication tokens work like an entry ticket with limited validity: they grant continuous access for as long as they are valid. As soon as the user logs out or leaves the application, the token is invalidated.]{.aside}


The [official documentation](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) contains a number of screenshots explaining
how to proceed. Keeping this documentation open in case of doubt, together with the instructions of the next exercise, we can create an authentication token.

::: {.callout-tip}
## Exercise 2: Create a _token_

Follow the
[official documentation](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token), giving the token only the `repo` rights[^droits-en].

[^droits-en]: As you can see, there are many different levels of rights. Your password actually has all these rights, which illustrates how dangerous it is if it is discovered, whether through an accidental disclosure or through someone malicious _hacking_ it. Using a _token_ makes your repository much safer since it cannot be deleted if the _token_ has limited rights. Moreover, if the main branch is protected, which is the default behaviour of `Github`, it will not be possible to destroy the repository history without a password.

To sum up, the steps should be as follows:

*Settings (account) > Developers Settings > Personal Access Token > Tokens (classic) > Generate a new token (classic) > "MyToken" > Expiration "90 days" > tick only "repo" > Generate token > Copy it*

__⚠️ Keep the page open__, the _token_ only appears once and we have not yet made the effort to store it somewhere durable. That will be the subject of the next exercise. Do not worry, though, if you lost the _token_ before you could save it: you can generate a new one by following the procedure above again.

:::

We have created a _token_ and, as indicated on the `Github` page or in the exercise instructions, it is not permanent. We therefore need to find a way to keep it somewhere. We will suggest several solutions. Writing it in a text file created with a notepad is not one of them; on the contrary, it is a very bad practice.

::: {.callout-important}

It is important never to store a _token_, let alone your password, in a project.
It is possible to store a password or *token* in a secure and durable way
with the `Git` *credential helper*. It is presented later on.

If it is not possible to use the `Git` *credential helper*, a password
or _token_ can be stored securely in
a password manager such as [Keepass](https://keepass.fr/).

Never store a `Github` token, or worse a password, in an unencrypted
text file. Password managers
(such as [Keepass](https://keepass.fr/), recommended by ANSSI, the French national cybersecurity agency)
are easy
to use and only keep on the computer a
hashed version of the password that can only be decrypted with a password
known to you alone.

:::



::: {.callout-tip}
## Exercise 3: store your token (for `SSPCloud` users)

The `SSPCloud` offers a token storage service that can then easily be used to authenticate to `Github` when using `VSCode` or `Jupyter`.

* Copy the token displayed on the `Github` page you opened earlier. Do not select the characters by hand, use the dedicated copy button ({{< fa solid clipboard >}})
* Click on the ["My Account"](https://datalab.sspcloud.fr/account/) section of the `SSPCloud` (*Mon Compte* if the interface is in French). Go to the `Git` tab and paste the value you copied.

You can stop at this point, we will use this token in the next exercise.

:::

::: {.callout-tip}
## Exercise 3bis: store your token (for people without `SSPCloud` access)

The recommended solution is to store your token in a password manager such as
[Keepass](https://keepass.fr/) (recommended by ANSSI). It is software that stores, in encrypted form, the passwords kept in it, following the logic of a digital safe.

Beyond the benefit of storing a Github token for this course, such software is very handy day to day and secures access to sensitive digital services. It also includes strong password generators that reduce the risk of digital identity theft by making techniques like [brute-force attacks](https://en.wikipedia.org/wiki/Brute-force_attack) almost impossible.

:::

::::
