:::: {.content-visible when-profile="fr"}

# Avant de démarrer: créer un compte `Github` et créer une copie de travail

La première étape se fait sur [`Github`](https://github.com). et consiste à se créer un compte sur cette plateforme.

::: {.callout-tip}
## Exercice 1 : Créer un compte `Github`

_Il est important de suivre pas à pas les consignes, chaque étape est importante_

1. Si vous n'en avez pas déjà un, créer un compte sur [github.com](https://github.com)
2. Créer un dépôt en suivant les consignes ci-dessous.
  + __Créer ce dépôt privé__, cela permettra
dans l'exercice 2 d'activer notre jeton. Vous pourrez le rendre public
après l'exercice 2, c'est comme vous le souhaitez.
  + __Créer ce dépôt avec un `README.md`__ en cliquant sur la case `Add a README file`
* Ajouter un `.gitignore` en sélectionnant le modèle `Python`

*Connexion sur <a href="https://github.com">https://github.com</a> > + (en haut de la page) > New repository > Renseigner le "Repository name" > Cocher "private" > "Create repository"*
[👉️ __Dépôt__: arborescence de fichiers dont on veut conserver l'historique dans une place commune.]{.aside}

:::

::::

:::: {.content-visible when-profile="en"}

# Before starting: create a `Github` account and a working copy

The first step takes place on [`Github`](https://github.com) and consists in creating an account on this platform.

::: {.callout-tip}
## Exercise 1: Create a `Github` account

_It is important to follow the instructions step by step, every step matters_

1. If you do not already have one, create an account on [github.com](https://github.com)
2. Create a repository following the instructions below.
  + __Create this repository as private__, this will allow us to
activate our token in exercise 2. You can make it public
after exercise 2, it is up to you.
  + __Create this repository with a `README.md`__ by ticking the `Add a README file` box
* Add a `.gitignore` by selecting the `Python` template

*Log in at <a href="https://github.com">https://github.com</a> > + (at the top of the page) > New repository > Fill in the "Repository name" > Tick "private" > "Create repository"*
[👉️ __Repository__: file tree whose history we want to keep in a common place.]{.aside}

:::

::::
