:::: {.content-visible when-profile="fr"}

## Le fichier `.gitignore`

Lorsqu'on utilise `Git`, il y a des fichiers qu'on ne veut pas partager
ou dont on ne veut pas suivre les modifications (typiquement les grosses bases de données).

C'est le fichier `.gitignore`
qui gère les fichiers exclus du contrôle de version.
Lors de la création du projet sur `GitHub`, nous avons demandé la création d'un fichier `.gitignore`, qui se situe à la racine du projet. Il spécifie l'ensemble des fichiers qui seront toujours exclus de l'indexation faite par `Git`.
[👉️ `.gitignore`: fichier stockant un ensemble de règles de fichiers ne devant pas être suivis par `Git`.]{.aside}


::: {.callout-tip}
## Exercice 6: le fichier `.gitignore`

1️⃣ Ouvrir le fichier `.gitignore` et observer
quelques règles écrites dedans

<details>

<summary>
Afficher ce fichier quand on utilise `Jupyter`
</summary>

Par défaut, le fichier `.gitignore` n'est pas affiché car
les fichiers `.*` sont des fichiers de configuration. Il faut activer
une option pour l'afficher. Tout en haut
de `Jupyter`, cliquer sur `View -> Show Hidden Files`

</details>

2️⃣ Créer un dossier `data` à la racine du projet et créer à l'intérieur de celui-ci un fichier `data/raw.csv` avec une ligne de données quelconque. Regardez l'onglet `Git` et remarquez la présence du fichier dans les changements à valider. __Ne pas ajouter à la _staging area_ et ne pas committer ce fichier__.

3️⃣ Ajouter la ligne `data/` dans le `.gitignore` (c'est un fichier texte modifiable), n'oubliez pas de sauvegarder. Retourner sur l'onglet `Git` et observer le changement. Comprenez-vous ce qu'il se passe ? 

4️⃣ Créer un fichier `raw2.csv` à la racine et un fichier `data/read_data.py` avec une ligne de code `Python` (le contenu du fichier n'est pas important).  

5️⃣ Retourner sur l'onglet `Git` et observer le changement de votre dépôt. 

:::


```{ojs}
//| echo: false
html`${containerQuestionGit2}`
```

```{ojs}
//| echo: false
//| output: false
containerQuestionGit2 = {
  // The container div for all the elements
  let container = html`
    <div class="question-container">
    <div class="question-text">${textQuestion2}</div>
    <div class="question-input">${viewof questionGit2}</div><br>
    <div class="question-message">${messageQuestion2Response}</div>
    </div>
  `;
  
  return container;
}
```

```{ojs}
//| output: false
textQuestion2 = md`__❓ **Question** : quelle règle faudrait-il mettre dans notre \`.gitignore\`__`
```


```{ojs}
//| echo: false
//| output: false
viewof questionGit2 = Inputs.radio(
  [
    '\`data/\` est une bonne règle pour mon \`.gitignore\`',
    'Il faudrait mettre \`data/*.csv\`',
    'Il faudrait mettre \`*.csv\`',
    'Je ne sais pas'],
  {disabled: ['Je ne sais pas'], value: 'Je ne sais pas', format: x => md`${x}`}
)
```

```{ojs}
//| echo: false
//| output: false
messageQuestion2 = [
  md`❌ __Pourtant le fichier \`raw2.csv/\` n'est pas ignoré et le fichier \`data/read_data.py\` est ignoré. Certes ils sont placés à un endroit non logique mais peut-être avez-vous mis ces fichiers à cette endroit volontairement.__`,
  md`❌ __Le fichier \`raw2.csv\` est mal placé, pour que cette règle s'applique, il faudrait le déplacer. Ou faire une règle plus conservatrice__`,
  md`✅ __C'est une bonne réponse ! C'est une règle certes conservatrice mais qui vous évitera de divulguer des données confidentielles sans faire exprès (voir 👇️)__`,
  md``
]
```

```{ojs}
//| echo: false
//| output: false
messageQuestion2Response = {
  let message;
  
  switch (questionGit2) {
    case '\`data/\` est une bonne règle pour mon \`.gitignore\`':
      message = messageQuestion2[0];
      break;
      
    case "Il faudrait mettre \`data/*.csv\`":
      message = messageQuestion2[1];
      break;
      
    case "Il faudrait mettre \`*.csv\`":
      message = messageQuestion2[2];
      break;

    case 'Je ne sais pas':
      message = messageQuestion2[3];
      break;
      
    default:
      message = md``; // Default case if none match, empty message
  }
  
  return message;
}
```


```{ojs}
textQuestion3
```

```{ojs}
//| output: false
textQuestion3 = md`__❓ **Question** : que se passe-t-il lorsque l'on ajoute au \`.gitignore\` des fichiers qui ont déjà été *commit* sur le projet Git ?__`
```

Il ne faut pas négliger le `.gitignore`. 

`Git` est un système de contrôle de version qui est pensé pour des fichiers textes, pas des fichiers de données. Contrairement aux fichiers texte où `Git` peut contrôler ligne à ligne les évolutions, ce qui en fait un gestionnaire de version utile, les fichiers de données sont trop complexes pour ce suivi fin, ce qui fait que chaque modification de ces fichiers, souvent lourds (plusieurs Méga Octets), revient à dupliquer le fichier dans la mémoire de `Git` (plus de détails sur les alternatives dans @tip-data).

Outre cette raison technique qui explique qu'on veuille exclure les fichiers de données du contrôle de version, il ne faut pas oublier que les données exploitées par les _data scientists_ sont souvent confidentielles, collectées pour des finalités bien définies ou ayant un intérêt stratégique qu'une divulgation à des concurrents pourait fragiliser. Partager des données au monde entier peut coûter très cher en vertu du RGPD dont les amendes peuvent aller jusqu'à 4% du chiffre d'affaires mondial.

Ce fichier `.gitignore` fait ainsi office de garde-fou. Il est utile d'être conservateur avec celui-ci quitte à autoriser, au cas par cas et de manière consciente, des dérogations. Pour cette raison, il est recommandé d'ajouter de nombreuses extensions classiques de données à celui-ci: `*.xlsx`, `*.csv`, `*.parquet`...


::: {#tip-data .callout-tip collapse="true"}
## Si les données ne vont pas sur `Github`, où les stocker ?

Il est plus pertinent de stocker des données dans des environnements _ad hoc_. Pour cela, l'état de l'art dans les technologies _cloud_ est d'utiliser un système de stockage spécialisé qui suit un protocole nommé `S3`. Ce dernier a été développé à l'origine par Amazon pour son _cloud_ commercial AWS avant d'être rendu _open source_. Cela permet ainsi d'avoir des infrastructures _cloud_ qui utilisent cette technologie indépendamment d'Amazon. 

`Github` apparaît certes pratique pour stocker des données. Mais il n'y a pas de _free lunch_. Ceci a d'abord un coût environnemental : `Git`, et donc _a fortiori_ `Github`, n'étant pas des systèmes de stockage de bases de données, ils n'optimisent pas le stockage de celles-ci. Il serait bon de ne pas faire croître plus que nécessaire, par du gaspillage numérique, l'empreinte carbone du numérique, déjà en croissance [@arcep2019]. Ensuite, ce choix, à l'origine pratique, s'avère souvent coûteux à long terme. Si la donnée archivée avec `Git` évolue fréquemment, la duplication inévitable qu'implique celle-ci fera exploser la volumétrie du dépôt. A partir d'un certain seuil, il faudra basculer vers des solutions complexes comme `Git large file storage (LFS)` ce qui est clairement évitable avec de la discipline. Au contraire, avec des systèmes de stockage pensés pour de la donnée, comme le protocole `S3`, le stockage et le traitement de celle-ci sont optimisés. C'est ce qui distingue les systèmes de stockage de données comme `S3` d'autres systèmes de stockages pensés pour des fichiers, indépendamment de leur format, comme `Drive` qui n'est pas adapté aux besoins des _data scientists_.

Stocker de la donnée est coûteux pour les fournisseurs de _cloud_ et il n'est pas étonnant que ces derniers proposent rarement des offres gratuites de volumes importants. Les utilisateurs.trices du `SSPCloud` bénéficient d'un système de stockage associé à la plateforme et suivant le protocole S3. Plus d'éléments dans le [chapitre consacré](/modern-ds/s3.qmd) et dans le cours de 3e année de l'ENSAE de [Mise en production de projets _data science_](https://ensae-reproductibilite.github.io/website/).

:::

::::

:::: {.content-visible when-profile="en"}

## The `.gitignore` file

When using `Git`, there are files you do not want to share
or whose changes you do not want to track (typically large databases).

It is the `.gitignore` file
that manages the files excluded from version control.
When creating the project on `GitHub`, we asked for a `.gitignore` file to be created, located at the root of the project. It specifies all the files that will always be excluded from `Git`'s indexing.
[👉️ `.gitignore`: file storing a set of rules for files that must not be tracked by `Git`.]{.aside}


::: {.callout-tip}
## Exercise 6: the `.gitignore` file

1️⃣ Open the `.gitignore` file and look at
some of the rules written in it

<details>

<summary>
Display this file when using `Jupyter`
</summary>

By default, the `.gitignore` file is not displayed because
`.*` files are configuration files. You need to enable
an option to display it. At the very top
of `Jupyter`, click on `View -> Show Hidden Files`

</details>

2️⃣ Create a `data` folder at the root of the project and, inside it, create a file `data/raw.csv` with any line of data. Look at the `Git` tab and notice that the file appears among the changes to be validated. __Do not add this file to the _staging area_ nor commit it__.

3️⃣ Add the line `data/` to the `.gitignore` (it is an editable text file), do not forget to save. Go back to the `Git` tab and observe the change. Do you understand what is happening?

4️⃣ Create a file `raw2.csv` at the root and a file `data/read_data.py` with a line of `Python` code (the content of the file does not matter).

5️⃣ Go back to the `Git` tab and observe the change in your repository.

:::


```{ojs}
//| echo: false
html`${containerQuestionGit2}`
```

```{ojs}
//| echo: false
//| output: false
containerQuestionGit2 = {
  // The container div for all the elements
  let container = html`
    <div class="question-container">
    <div class="question-text">${textQuestion2}</div>
    <div class="question-input">${viewof questionGit2}</div><br>
    <div class="question-message">${messageQuestion2Response}</div>
    </div>
  `;

  return container;
}
```

```{ojs}
//| output: false
textQuestion2 = md`__❓ **Question**: which rule should we put in our \`.gitignore\`?__`
```


```{ojs}
//| echo: false
//| output: false
viewof questionGit2 = Inputs.radio(
  [
    '\`data/\` is a good rule for my \`.gitignore\`',
    'We should put \`data/*.csv\`',
    'We should put \`*.csv\`',
    "I don't know"],
  {disabled: ["I don't know"], value: "I don't know", format: x => md`${x}`}
)
```

```{ojs}
//| echo: false
//| output: false
messageQuestion2 = [
  md`❌ __Yet the file \`raw2.csv\` is not ignored and the file \`data/read_data.py\` is ignored. Admittedly they are placed somewhere illogical but perhaps you put these files there on purpose.__`,
  md`❌ __The file \`raw2.csv\` is misplaced; for this rule to apply, it would need to be moved. Or use a more conservative rule__`,
  md`✅ __That is a good answer! It is admittedly a conservative rule but it will keep you from accidentally disclosing confidential data (see 👇️)__`,
  md``
]
```

```{ojs}
//| echo: false
//| output: false
messageQuestion2Response = {
  let message;

  switch (questionGit2) {
    case '\`data/\` is a good rule for my \`.gitignore\`':
      message = messageQuestion2[0];
      break;

    case "We should put \`data/*.csv\`":
      message = messageQuestion2[1];
      break;

    case "We should put \`*.csv\`":
      message = messageQuestion2[2];
      break;

    case "I don't know":
      message = messageQuestion2[3];
      break;

    default:
      message = md``; // Default case if none match, empty message
  }

  return message;
}
```


```{ojs}
textQuestion3
```

```{ojs}
//| output: false
textQuestion3 = md`__❓ **Question**: what happens when you add to the \`.gitignore\` files that have already been *committed* to the Git project?__`
```

The `.gitignore` should not be neglected.

`Git` is a version control system designed for text files, not data files. Unlike text files, where `Git` can track changes line by line, which makes it a useful version manager, data files are too complex for this fine-grained tracking, so every change to these files, which are often heavy (several megabytes), amounts to duplicating the file in `Git`'s memory (more details on the alternatives in @tip-data).

Besides this technical reason for wanting to exclude data files from version control, do not forget that the data used by _data scientists_ is often confidential, collected for well-defined purposes or of strategic interest that disclosure to competitors could weaken. Sharing data with the whole world can be very costly under the GDPR, whose fines can reach 4% of worldwide turnover.

This `.gitignore` file thus acts as a safeguard. It is useful to be conservative with it, even if it means allowing exceptions, case by case and consciously. For this reason, it is recommended to add many classic data extensions to it: `*.xlsx`, `*.csv`, `*.parquet`...


::: {#tip-data .callout-tip collapse="true"}
## If data does not go on `Github`, where should it be stored?

It is more relevant to store data in _ad hoc_ environments. For this, the state of the art in _cloud_ technologies is to use a specialised storage system that follows a protocol called `S3`. It was originally developed by Amazon for its commercial AWS _cloud_ before being made _open source_. This makes it possible to have _cloud_ infrastructures that use this technology independently of Amazon.

`Github` admittedly seems convenient for storing data. But there is no such thing as a free lunch. This first has an environmental cost: `Git`, and _a fortiori_ `Github`, are not database storage systems, so they do not optimise the storage of data. We should avoid increasing the carbon footprint of digital technology, already growing [@arcep2019], any more than necessary through digital waste. Then, this choice, originally convenient, often proves costly in the long run. If the data archived with `Git` changes frequently, the unavoidable duplication it implies will make the volume of the repository explode. Beyond a certain threshold, you will have to switch to complex solutions such as `Git large file storage (LFS)`, which is clearly avoidable with discipline. In contrast, with storage systems designed for data, such as the `S3` protocol, storing and processing data are optimised. This is what distinguishes data storage systems like `S3` from other storage systems designed for files, regardless of their format, like `Drive`, which is not suited to the needs of _data scientists_.

Storing data is expensive for _cloud_ providers and it is no surprise that they rarely offer free plans for large volumes. `SSPCloud` users benefit from a storage system attached to the platform and following the S3 protocol. More details in the [dedicated chapter](/modern-ds/s3.qmd) and in the ENSAE 3rd-year course [Putting _data science_ projects into production](https://ensae-reproductibilite.github.io/website/) (in French).

:::

::::
