:::: {.content-visible when-profile="fr"}

# Premières interactions avec `Github` depuis sa copie de travail

Jusqu'à présent, après avoir cloné le dépôt, on a travaillé uniquement
sur notre copie locale. On n'a pas cherché à interagir à nouveau 
avec `Github`. 

Il est tout à fait possible de faire du contrôle de version sans
mettre en place de dépôt distant. Cependant, 

* c'est dangereux puisque le dépôt distant fait office de sauvegarde 
d'un projet. Sans dépôt distant, on peut tout perdre en cas de problème
sur la copie locale de travail ;
* c'est désirer être moins efficace car, comme nous allons le montrer, les
fonctionalités des plateformes `Github` et `Gitlab` sont également très 
bénéfiques lorsqu'on travaille tout seul. 


Interagir avec le dépôt distant consiste à récupérer les nouveautés sur celui-ci ou envoyer nos dernières modifications vers ce dépôt centralisateur. En pratique, on peut donc résumer 95% de la pratique quotidienne de `Git` en trois mots:

* `commit` : je valide les modifications que j'ai faites en local avec un message qui les explique
* `pull` : je récupère la dernière version des codes du dépôt distant (opération dite `fetch`) et je la fusionne avec mes changements, si j'en ai fait (opération dite `merge`)
* `push` : je transmets mes modifications validées au dépôt distant

Nous avons déjà vu le premier, nous allons voir maintenant les deux nouveaux termes. 
Avant cela, on peut revenir sur une commande déjà évoquée `git remote -v`. Le dépôt distant s'appelle `remote` en langage Git. L'option `-v` (*verbose*)
permet de lister le(s) dépôt(s) distant(s). 

En ouvrant un terminal dans `VSCode`, en tapant `git remote -v` dans celui-ci, vous devriez avoir un résultat similaire à celui-ci:

```shell
origin  https://<PAT>@github.com/<username>/<projectname>.git (fetch)
origin  https://<PAT>@github.com/<username>/<projectname>.git (push)
```

Plusieurs informations sont intéressantes dans ce résultat. D'abord on 
retrouve bien l'url qu'on avait renseigné à `Git` lors de l'opération
de clonage. Ensuite, on remarque un terme `origin`. C'est un alias
pour l'url qui suit. Cela évite d'avoir, à chaque fois, à taper l'ensemble
de l'url, ce qui peut être pénible et source d'erreur.

`fetch` et `push`
sont là pour nous indiquer qu'on récupère (`fetch`) des modifications
d'`origin` mais qu'on envoie également (`push`) des modifications vers
celui-ci. Généralement, les url de ces deux dépôts sont les mêmes mais cela peut
arriver, lorsqu'on contribue à des projets opensource qu'on n'a pas créé, 
qu'ils diffèrent. Ceci sera expliqué dans le prochain chapitre lorsque nous aborderons le sujet de la collaboration. 

## Envoyer des modifications sur le dépôt distant (`push`)

::: {.callout-tip}
## Exercice 7 : Interagir avec `Github`

Il convient maintenant d'envoyer les fichiers sur le dépôt distant. 

1️⃣ Si vous ne l'avez pas déjà fait, ajouter la règle `*.csv` dans votre `.gitignore`. Avec l'interface graphique, ajouter tous les fichiers en attente dans l'index (`git add`) et faites un _commit_ (`git commit`).  
2️⃣ Cliquer sur le bouton <i class="fa-solid fa-arrows-rotate"></i> Sync changes <i class="fa-solid fa-arrow-up"></i>

L'équivalent de ces deux questions serait, en ligne de commande:

```{python}
#| eval: false
git add -u
git commit -m "Le titre du commit"
git push origin main #<1>
```
1. Cela signifie: *"git envoie (`push`) mes modifications sur la 
branche `main` (la branche sur laquelle on a travaillé, on reviendra
dessus) vers mon dépôt (alias
`origin`)"*


:::


## Récupérer des modifications depuis le dépôt distant (`pull`)

La deuxième manière d'interagir avec le dépôt est de récupérer des
résultats disponibles en ligne sur sa copie de travail. On appelle
cela `pull`. 

Pour le moment, vous êtes tout seul sur le dépôt. Il n'y a donc pas de 
partenaire pour modifier un fichier dans le dépôt distant. On va simuler ce
cas en utilisant l'interface graphique de `Github` pour modifier
des fichiers. On rapatriera les résultats en local dans un deuxième temps. 

::: {.callout-tip}
## Exercice 8: Rapatrier des modifications en local

1️⃣ Se rendre sur votre dépôt depuis l'interface <https://github.com>

* Se placer sur le fichier `README.md` et cliquer sur le bouton `Edit this file`, qui prend la forme d'un icône de crayon.

2️⃣ Changer le titre du `README.md`. Sautez une ligne à la fin de votre fichier et entrez le texte que vous désirez, sans ponctuation. Par exemple,

~~~markdown
le chêne un jour dit au roseau
~~~

3️⃣ Cliquez sur l'onglet `Preview` pour voir le texte mis en forme au format `Markdown`

4️⃣  Rédiger un titre et un message complémentaire pour faire le `commit`. Conserver
l'option par défaut `Commit directly to the main branch`

5️⃣ Editer à nouveau le `README` en cliquant sur le crayon juste au dessus
de l'affichage du contenu du `README`.

Ajouter une deuxième phrase et corrigez la
ponctuation de la première. Ecrire un message de commit et valider.

~~~markdown
Le Chêne un jour dit au roseau :
Vous avez bien sujet d'accuser la Nature
~~~

6️⃣ Au dessus de l'aborescence des fichiers, vous devriez voir s'afficher le
titre du dernier commit. Vous pouvez cliquer dessus pour voir la modification
que vous avez faite.

7️⃣ Les résultats sont sur le dépôt distant mais ne sont pas sur votre
dossier de travail dans `Jupyter` ou `VSCode`. Il faut re-synchroniser votre copie locale
avec le dépôt distant :

* Sur `VSCode`, cliquez simplement sur `... > Pull` à côté du bouton qui permet
de visualiser le graphe Git.
* Avec l'interface `Jupyter`, si cela est possible, appuyez tout simplement sur la petite
flèche vers le bas, qui est celle qui a désormais la pastille orange.
* Si cette flèche n'est pas disponible ou si vous travaillez dans un autre
environnement, vous pouvez utiliser la ligne de 
commande et taper

```{python}
#| eval: false
git pull origin main #<1>
```
1. Cela signifie : *"git récupère (`pull`) les modifications sur la 
branche `main` vers mon dépôt (alias
`origin`)"*


8️⃣ Regarder à nouveau l'historique des commits. Cliquez sur le
dernier commit et affichez les changements sur le fichier. Vous pouvez
remarquer la finesse du contrôle de version : `Git` détecte au sein de
la première ligne de votre texte que vous avez mis des majuscules
ou de la ponctuation. 


:::

L'opération `pull` permet : 

1. A votre système local de vérifier les modifications sur le dépôt distant
que vous n'auriez pas faites (cette opération s'appelle `fetch`)
2. De les fusionner s'il n'y a pas de conflit de version ou si les conflits de
version sont automatiquement fusionnables (deux modifications d'un fichier mais
qui ne portent pas sur le même emplacement).

::::

:::: {.content-visible when-profile="en"}

# First interactions with `Github` from your working copy

So far, after cloning the repository, we have worked only
on our local copy. We have not tried to interact again
with `Github`.

It is perfectly possible to do version control without
setting up a remote repository. However,

* it is dangerous since the remote repository acts as a backup
of a project. Without a remote repository, you can lose everything if there is a problem
with the local working copy;
* it means choosing to be less efficient because, as we will show, the
features of the `Github` and `Gitlab` platforms are also very
beneficial when working alone.


Interacting with the remote repository consists in retrieving what is new on it or sending our latest changes to this central repository. In practice, we can therefore summarise 95% of daily `Git` practice in three words:

* `commit`: I validate the changes I made locally with a message explaining them
* `pull`: I retrieve the latest version of the code from the remote repository (an operation called `fetch`) and merge it with my changes, if I made any (an operation called `merge`)
* `push`: I send my validated changes to the remote repository

We have already seen the first one, we will now see the two new terms.
Before that, we can come back to a command already mentioned, `git remote -v`. The remote repository is called a `remote` in Git language. The `-v` option (*verbose*)
lists the remote repository(ies).

By opening a terminal in `VSCode` and typing `git remote -v` in it, you should get a result similar to this one:

```shell
origin  https://<PAT>@github.com/<username>/<projectname>.git (fetch)
origin  https://<PAT>@github.com/<username>/<projectname>.git (push)
```

Several pieces of information are interesting in this result. First, we
find the url we gave to `Git` during the cloning operation. Then, we notice a term `origin`. It is an alias
for the url that follows. It saves us from having to type the whole
url every time, which can be tedious and error-prone.

`fetch` and `push`
are there to tell us that we retrieve (`fetch`) changes from
`origin` but also send (`push`) changes to
it. Generally, the urls of these two repositories are the same but it can
happen, when contributing to open-source projects that we did not create,
that they differ. This will be explained in the next chapter when we tackle the subject of collaboration.

## Sending changes to the remote repository (`push`)

::: {.callout-tip}
## Exercise 7: Interact with `Github`

We now need to send the files to the remote repository.

1️⃣ If you have not already done so, add the rule `*.csv` to your `.gitignore`. With the graphical interface, add all pending files to the index (`git add`) and make a _commit_ (`git commit`).
2️⃣ Click on the <i class="fa-solid fa-arrows-rotate"></i> Sync changes <i class="fa-solid fa-arrow-up"></i> button

The equivalent of these two steps on the command line would be:

```{python}
#| eval: false
git add -u
git commit -m "The commit title"
git push origin main #<1>
```
1. This means: *"git sends (`push`) my changes on the
`main` branch (the branch we worked on, we will come back
to it) to my repository (alias
`origin`)"*


:::


## Retrieving changes from the remote repository (`pull`)

The second way of interacting with the repository is to retrieve
results available online onto your working copy. This is called
`pull`.

For now, you are alone on the repository. There is therefore no
partner to modify a file in the remote repository. We will simulate this
case by using the `Github` graphical interface to modify
files. We will bring the results back locally in a second step.

::: {.callout-tip}
## Exercise 8: Bring changes back locally

1️⃣ Go to your repository from the <https://github.com> interface

* Go to the `README.md` file and click on the `Edit this file` button, which looks like a pencil icon.

2️⃣ Change the title of the `README.md`. Skip a line at the end of your file and enter the text you want, without punctuation. For example,

~~~markdown
the oak one day said to the reed
~~~

3️⃣ Click on the `Preview` tab to see the text formatted in `Markdown`

4️⃣  Write a title and an additional message to make the `commit`. Keep
the default option `Commit directly to the main branch`

5️⃣ Edit the `README` again by clicking on the pencil just above
the display of the `README` content.

Add a second sentence and fix the
punctuation of the first one. Write a commit message and validate.

~~~markdown
The Oak one day said to the Reed:
You have good reason to accuse Nature
~~~

6️⃣ Above the file tree, you should see the
title of the last commit. You can click on it to see the change
you made.

7️⃣ The results are on the remote repository but are not in your
working folder in `Jupyter` or `VSCode`. You need to re-synchronise your local copy
with the remote repository:

* In `VSCode`, simply click on `... > Pull` next to the button that lets you
view the Git graph.
* With the `Jupyter` interface, if possible, simply press the small
down arrow, the one that now has the orange badge.
* If this arrow is not available or if you work in another
environment, you can use the command
line and type

```{python}
#| eval: false
git pull origin main #<1>
```
1. This means: *"git retrieves (`pull`) the changes on the
`main` branch to my repository (alias
`origin`)"*


8️⃣ Look at the commit history again. Click on the
last commit and display the changes on the file. You can
notice how fine-grained version control is: `Git` detects, within
the first line of your text, that you added capital letters
or punctuation.


:::

The `pull` operation allows:

1. Your local system to check for changes on the remote repository
that you have not made (this operation is called `fetch`)
2. To merge them if there is no version conflict or if the version conflicts
can be merged automatically (two modifications of a file that do not
affect the same location).

::::
