:::: {.content-visible when-profile="fr"}

## Les conflits

Au cours du dernier exercice du chapitre précédent, nous avons, sans vraiment l'expliquer, découvert le principe du _merge_ (ou fusion, en Français). Les fusions de versions consistent à réconcilier deux versions d'un code. Cela peut se faire en privilégiant l'une sur l'autre ou bien en choisissant, dans les passages qui divergent, parfois l'une et parfois l'autre. On parle de conflits pour désigner une situation où un même fichier présente deux versions différentes qui doivent être réconciliées. 

`Git` simplifie énormément la gestion de conflits, c'est l'une des raisons de son succès. Si vous avez déjà partagé du code par mail en équipe, vous devez savoir que réconcilier des versions est extrêmement fastidieux : il faut, plus ou moins ligne à ligne, vérifier que la version que vous avez reçu par mail ne diffère pas de la vôtre, que vous avez fait évoluer en parallèle. Grâce au suivi fin de l'évolution d'un fichier que permet `Git`, cette gestion de conflits sera facilitée. Il faudra tout de même privilégier une version sur l'autre mais cela sera plus rapide et plus fiable. 

Si `Git` offre des fonctionnalités intéressantes, pour la gestion des conflits, ce n'est néanmoins pas une excuse pour être désorganisé. Comme nous allons le voir dans les prochains exercices, on a certes des chapitres

::: {.callout-tip}
## Méthode pour les merges

Lors du chapitre précédent, nous avons fait un _merge_ de notre branche `issue-1` vers `main`, notre branche principale. Nous sommes passés par l'interface de `Github` pour faire cela. Il s'agit de la méthode recommandée pour les _merges_ vers `main`. Cela permet de garder une trace explicite de ceux-ci (par exemple [ici](https://github.com/linogaliana/python-datascientist/pulls?q=is%3Apr+is%3Aclosed)), sans avoir à chercher dans l'arborescence, parfois complexe, d'un projet.

La bonne pratique veut qu'on fasse un `squash commit` pour éviter une inflation du nombre de commits dans `main`: les branches ont vocation à proposer une multitude de petits commits, les modifications dans `main` doivent être simples à tracer d'où le fait de modifier des petits bouts de code. 

Comme on l'a fait dans un exercice précédent, il est très pratique d’ajouter dans le corps du message  `close #xx` où `xx` est le numéro d'une *issue* associée à la `pull request`. Lorsque la `pull request` sera fusionnée, l’*issue* sera automatiquement fermée et un lien sera créé entre l'`issue` et la `pull request`. Cela vous permettra de comprendre, plusieurs mois ou années plus tard comment et pourquoi telle ou telle fonctionnalité a été implémentée.

En revanche, l'intégration des dernières modifications de `main` vers une branche se fait en local. Si votre branche est en conflit, **le conflit doit être résolu dans la branche et pas dans main**. 
`main` doit toujours rester propre. 
:::

::::

:::: {.content-visible when-profile="en"}

## Conflicts

During the last exercise of the previous chapter, we discovered, without really explaining it, the principle of a _merge_. Merging versions consists in reconciling two versions of a piece of code. This can be done by favouring one over the other or by choosing, in the passages that diverge, sometimes one and sometimes the other. We speak of conflicts to describe a situation where the same file has two different versions that must be reconciled.

`Git` greatly simplifies conflict management, which is one of the reasons for its success. If you have ever shared code by email in a team, you know that reconciling versions is extremely tedious: you have to check, more or less line by line, that the version you received by email does not differ from yours, which you have developed in parallel. Thanks to the fine-grained tracking of a file's evolution that `Git` allows, this conflict management is made easier. You will still have to favour one version over the other but it will be faster and more reliable.

While `Git` offers interesting features for conflict management, this is not an excuse to be disorganised. As we will see in the next exercises, we do have chapters

::: {.callout-tip}
## Method for merges

In the previous chapter, we _merged_ our `issue-1` branch into `main`, our main branch. We went through the `Github` interface to do so. This is the recommended method for _merges_ into `main`. It keeps an explicit trace of them (for example [here](https://github.com/linogaliana/python-datascientist/pulls?q=is%3Apr+is%3Aclosed)), without having to search the sometimes complex tree of a project.

Good practice is to make a `squash commit` to avoid an inflation of the number of commits in `main`: branches are meant to hold a multitude of small commits, while changes in `main` must be easy to trace, hence the idea of modifying small pieces of code.

As we did in a previous exercise, it is very handy to add `close #xx` in the body of the message, where `xx` is the number of an *issue* associated with the `pull request`. When the `pull request` is merged, the *issue* will be closed automatically and a link will be created between the `issue` and the `pull request`. This will let you understand, several months or years later, how and why a given feature was implemented.

On the other hand, integrating the latest changes from `main` into a branch is done locally. If your branch is in conflict, **the conflict must be resolved in the branch and not in main**.
`main` must always remain clean.
:::

::::
