:::: {.content-visible when-profile="fr"}

# Conclusion

Ces chapitres consacrés à `Git` ont permis de démystifier ce logiciel en illustrant, par la pratique, les principaux concepts et la gymnastique quotidienne. Ils visent à faire économiser de précieuses heures car l'apprentissage de `Git` en autodidacte est souvent frustrant et incomplet. Il est indispensable de garder cette habitude de faire du `Git` sur ses projets. Ces derniers seront de meilleure qualité.

Nous n'avons vu que les fonctionnalités basiques de `Git` et de `Github`. L'objet du cours de 3e année de l'ENSAE de ["Mise en production de projets _data science_"](https://ensae-reproductibilite.github.io/website/) est de faire découvrir d'autres fonctionnalités de `Git` et `Github` qui permettent de produire des projets plus ambitieux, plus fiables et plus évolutifs.

::::

:::: {.content-visible when-profile="en"}

# Conclusion

These chapters devoted to `Git` have helped demystify this software by illustrating, through practice, the main concepts and the daily routine. They aim to save you precious hours because learning `Git` on your own is often frustrating and incomplete. It is essential to keep the habit of using `Git` on your projects. They will be of better quality.

We have only seen the basic features of `Git` and `Github`. The purpose of the ENSAE 3rd-year course ["Putting _data science_ projects into production"](https://ensae-reproductibilite.github.io/website/) (in French) is to introduce other features of `Git` and `Github` that make it possible to produce more ambitious, more reliable and more scalable projects.

::::
