:::: {.content-visible when-profile="fr"}

# Mise en pratique

::: {.callout-tip}
## Exercice 1 : Interactions avec le dépôt distant


Cet exercice se fait par groupe de trois ou quatre. Il y aura deux rôles dans ce scénario :

- Une personne aura la responsabilité d'être **mainteneur**
- Deux à trois personnes seront **développeurs**. 

1️⃣ Le.la mainteneur.e crée un dépôt sur `Github` __sans cliquer sur l'option `Add a README`__. Créer un `.gitignore` selon le modèle `Python`. Il/Elle donne des droits au(x) développeur.euse(s) du projet (`Settings > Manage Access > Invite a collaborator`).

2️⃣ Chaque membre du projet, crée une copie locale du projet (un _clone_). Si vous avez un trou de mémoire, vous pouvez retourner au chapitre précédent pour vérifier la démarche.

3️⃣ Chaque membre du projet crée un fichier avec son nom et son prénom, selon cette structure `nom-prenom.md` en évitant les caractères spéciaux. Il écrit dedans trois phrases de son choix **sans ponctuation ni majuscules** (pour pouvoir effectuer une correction ultérieurement). Enfin, il _commit_ sur le projet __par le biais de l'extension visuelle__.


<details>
<summary>

En ligne de commande cela donnerait les commandes équivalentes

</summary>

~~~shell
git add nom-prenom.md
git commit -m "C'est l'histoire de XXXXX"
~~~

</details>


4️⃣ Chacun essaie d'envoyer (*push*) ses modifications locales sur le dépôt en passant par les boutons adéquats de l'extension visuelle. 


<details>
<summary>

En ligne de commande cela donnerait la commande équivalente

</summary>

~~~shell
git push origin main
~~~

</details>


5️⃣ A ce stade, une seule personne (la plus rapide) devrait ne pas avoir rencontré de rejet du `push`. C'est normal, avant d'accepter une modification `Git` vérifie en premier lieu la cohérence de la branche avec le dépôt distant. Le premier ayant fait un `push` a modifié le dépôt commun ; les autres doivent intégrer ces modifications dans leur version locale (*pull*) avant d'avoir le droit de proposer un changement.

Pour celui/celle/ceux dont le `push` a été refusé, il faudra faire un _pull_. Faire celui-ci en utilisant l'extension graphique de `VSCode`.

<details>
<summary>

En ligne de commande cela donnerait la commande équivalente

</summary>

~~~shell
git pull origin main
~~~

</details>


pour essayer de ramener les modifications distantes en local. 

6️⃣ Regarder l'arbre obtenu dans l'interface pour comprendre comment a été intégrée la modification de votre camarade ayant pu faire son `push` avant. 

Vous remarquerez que les commits de vos camarades sont intégrés tels quels à 
l'histoire du dépôt. 

7️⃣ Faire à nouveau un _push_. C'est fini pour la 2e personne. La dernière personne doit refaire, à nouveau, les étapes 5 à 7 (dans une équipe de quatre
il faudra encore le refaire une fois).

:::

__❓ Question : que se serait-il passé si les différents membres du groupe avaient effectué leurs modifications sur un seul et même fichier ?__

Le prochain exercice offre une réponse à cette question.

::::

:::: {.content-visible when-profile="en"}

# Putting it into practice

::: {.callout-tip}
## Exercise 1: Interactions with the remote repository


This exercise is done in groups of three or four. There will be two roles in this scenario:

- One person will be responsible for being the **maintainer**
- Two to three people will be **developers**.

1️⃣ The maintainer creates a repository on `Github` __without clicking on the `Add a README` option__. Create a `.gitignore` using the `Python` template. They give rights to the project developer(s) (`Settings > Manage Access > Invite a collaborator`).

2️⃣ Each member of the project creates a local copy of the project (a _clone_). If you have a memory lapse, you can go back to the previous chapter to check the procedure.

3️⃣ Each member of the project creates a file with their last name and first name, following this structure `lastname-firstname.md` and avoiding special characters. They write three sentences of their choice in it **without punctuation or capital letters** (so that a correction can be made later). Finally, they _commit_ on the project __through the visual extension__.


<details>
<summary>

On the command line, the equivalent commands would be

</summary>

~~~shell
git add lastname-firstname.md
git commit -m "This is the story of XXXXX"
~~~

</details>


4️⃣ Everyone tries to send (*push*) their local changes to the repository using the appropriate buttons of the visual extension.


<details>
<summary>

On the command line, the equivalent command would be

</summary>

~~~shell
git push origin main
~~~

</details>


5️⃣ At this stage, only one person (the fastest) should not have encountered a `push` rejection. This is normal: before accepting a change, `Git` first checks the consistency of the branch with the remote repository. The first person to have pushed modified the shared repository; the others must integrate these changes into their local version (*pull*) before being allowed to propose a change.

For those whose `push` was rejected, you will need to do a _pull_. Do it using the `VSCode` graphical extension.

<details>
<summary>

On the command line, the equivalent command would be

</summary>

~~~shell
git pull origin main
~~~

</details>


to try to bring the remote changes locally.

6️⃣ Look at the tree obtained in the interface to understand how the change from your teammate who could `push` earlier was integrated.

You will notice that your teammates' commits are integrated as they are into
the history of the repository.

7️⃣ _Push_ again. It is over for the 2nd person. The last person must redo steps 5 to 7 again (in a team of four
it will have to be done once more).

:::

__❓ Question: what would have happened if the different members of the group had made their changes on one and the same file?__

The next exercise offers an answer to this question.

::::
