:::: {.content-visible when-profile="fr"}

::: {.callout-tip}
## Exercice 2 : Gérer les conflits quand on travaille sur le même fichier

Dans la continuité de l'exercice précédent, chaque personne va travailler sur les fichiers des autres membres de l'équipe.

1️⃣ Les deux ou trois développeurs ajoutent la ponctuation et les majuscules du fichier du premier développeur.

2️⃣ Ils sautent une ligne et ajoutent une phrase (pas tous la même).

3️⃣ Valider les résultats avec un _commit_ et faire un _push_.

4️⃣ La personne la plus rapide n'a, normalement, rencontré aucune difficulté (elle peut s'arrêter temporairement pour regarder ce qui va se passer chez les voisins). Les autres voient leur `push` refusé et doivent faire un `pull`. 

💥 Il y a conflit, ce qui doit être signalé par un message du type :

```python
Auto-merging XXXXXX
CONFLICT (content): Merge conflict in XXXXXX.md
Automatic merge failed; fix conflicts and then commit the result.
```

5️⃣ Etudier le résultat de `git status` 

6️⃣ Si vous ouvrez les fichiers incriminés, vous devriez voir des balises du type

```python
<<<<<<< HEAD
this is some content to mess with
content to append
=======
totally different content to merge later
>>>>>>> new_branch_to_merge_later
```

qui sont mises en forme par `VSCode` comme dans la @fig-conflict.


7️⃣ Corriger les fichiers en choisissant, pour chaque bloc, la version qui vous convient grâce aux actions permises par Git (`Accept Current Change`...)

Faire un _commit_ avec le titre "Résolution du conflit par XXXX" où `XXXX` est votre nom.

8️⃣ Faire un push. Pour la dernière personne, refaire les opérations 4 à 8

:::

`Git` permet donc de travailler, en même temps, sur le même fichier et de limiter le nombre de gestes manuels nécessaires pour faire la fusion. Lorsqu'on travaille sur des bouts différents du même fichier, on n'a même pas besoin de faire de modification manuelle, la fusion peut être automatique.

`Git` est un outil très puissant. Mais, il ne remplace pas une bonne organisation du travail. Vous l'avez vu, ce mode de travail uniquement sur `main` peut être pénible. Les branches prennent tout leur sens dans ce cas. 

::::

:::: {.content-visible when-profile="en"}

::: {.callout-tip}
## Exercise 2: Handle conflicts when working on the same file

Continuing from the previous exercise, each person will work on the files of the other team members.

1️⃣ The two or three developers add the punctuation and capital letters to the first developer's file.

2️⃣ They skip a line and add a sentence (not all the same one).

3️⃣ Validate the results with a _commit_ and make a _push_.

4️⃣ The fastest person normally encountered no difficulty (they can pause temporarily to watch what will happen to their neighbours). The others see their `push` rejected and must do a `pull`.

💥 There is a conflict, which should be signalled by a message like:

```python
Auto-merging XXXXXX
CONFLICT (content): Merge conflict in XXXXXX.md
Automatic merge failed; fix conflicts and then commit the result.
```

5️⃣ Study the result of `git status`

6️⃣ If you open the offending files, you should see markers like

```python
<<<<<<< HEAD
this is some content to mess with
content to append
=======
totally different content to merge later
>>>>>>> new_branch_to_merge_later
```

which are formatted by `VSCode` as in @fig-conflict.


7️⃣ Fix the files by choosing, for each block, the version that suits you thanks to the actions allowed by Git (`Accept Current Change`...)

Make a _commit_ with the title "Conflict resolved by XXXX" where `XXXX` is your name.

8️⃣ Make a push. For the last person, redo operations 4 to 8

:::

`Git` therefore makes it possible to work, at the same time, on the same file and to limit the number of manual actions needed to do the merge. When working on different parts of the same file, there is not even a need to make a manual modification, the merge can be automatic.

`Git` is a very powerful tool. But it does not replace good work organisation. As you have seen, this way of working solely on `main` can be painful. Branches make full sense in this case.

::::
