---
title: "Git: faire un cadavre exquis"
date: 2020-09-30T13:00:00Z
draft: false
weight: 100
output: 
  html_document:
    keep_md: true
    self_contained: true
slug: exogit
---

## Pratique individuelle de Git

Les deux premières étapes se font sur `Github`


{{% panel status="exercise" title="Exercise 1: créer un compte Github" icon="fab fa-github" %}}

1. Si vous n'en avez pas déjà un, créer un compte sur Github
2. Créer un dépôt vide. Ce dépôt sera personnel, vous pouvez le rendre public
ou non, comme vous le souhaitez.
{{% /panel %}}

Maintenant, en local. Il faut ouvrir une invite de commande `git bash` (ou une
interface graphique connectée à `git bash`)

{{% panel status="exercise" title="Exercise 2: découvrir l'invite de commande" icon="fas fa-pencil-alt" %}}

1. Sur les postes ENSAE. Aller dans `Scientific Apps/Git`. Vous devriez voir
un raccourci `bash.exe`. Vous pouvez lancer l'application ; elle ouvre une 
invite de commande
2. Créer un dossier de travail, par exemple `Desktop/gitexo`. Dans `git bash`,
faire 

```shell
cd `Desktop/gitexo`
```

{{% /panel %}}


