:::: {.content-visible when-profile="fr"}

# Un cadavre exquis pour découvrir le travail collaboratif

Jusqu'à présent, nous avons découvert les vertus de `Git` dans un projet
individuel. Nous allons maintenant aller plus loin dans un projet 
collectif. Pour rappel, dans le chapitre précédent nous avons évoqué les concepts natifs de `Git` que sont dépôts local et distant (`remote`), l'opération de `clone`, _staging area_, `commit`, `push`, `pull`, les branches. Nous avons aussi évoqué certains concepts liés à la forge `Github` que sont l'authentification et les _issues_.

Maintenant, nous allons évoquer les enjeux liés au travail collaboratif, ce qui nous amènera, notamment, à évoquer les enjeux de la gestion de conflits. 

::::

:::: {.content-visible when-profile="en"}

# An exquisite corpse to discover collaborative work

So far, we have discovered the virtues of `Git` in an individual project. We will now go further with a
collective project. As a reminder, in the previous chapter we covered the native concepts of `Git`: local and remote repositories (`remote`), the `clone` operation, _staging area_, `commit`, `push`, `pull`, and branches. We also covered some concepts related to the `Github` forge: authentication and _issues_.

Now, we will discuss the challenges of collaborative work, which will lead us, in particular, to discuss the challenges of conflict management.

::::
