spooky: https://github.com/GU4243-ADS/spring2018-project1-ginnyqg/blob/master/data/spooky.csv

cog2023:
  raw: https://www.insee.fr/fr/statistiques/fichier/6800675/v_commune_2023.csv
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/cog_2023.csv

britishLibraryBooks: https://raw.githubusercontent.com/realpython/python-data-cleaning/master/Datasets/BL-Flickr-Images-Book.csv
koumoulApi: https://koumoul.com/data-fair/api/v1/datasets/dpe-france/lines
countyResults: https://raw.githubusercontent.com/tonmcg/US_County_Level_Election_Results_08-20/master/2020_US_County_Level_Presidential_Results.csv
MonteCristo: https://www.gutenberg.org/files/17989/17989-0.txt
codePostaux: https://datanova.laposte.fr/data-fair/api/v1/datasets/laposte-hexasmal/raw

velibHistoricalParquet: https://opendata.paris.fr/api/explore/v2.1/catalog/datasets/comptage-velo-donnees-compteurs/exports/parquet?lang=fr&timezone=Europe%2FParis
velibComptageVelo: https://opendata.paris.fr/explore/dataset/comptage-velo-donnees-compteurs/dataviz/?disjunctive.id_compteur&disjunctive.nom_compteur&disjunctive.id&disjunctive.name
velibEmplacementStations: https://opendata.paris.fr/explore/dataset/velib-emplacement-des-stations/download/?format=geojson&timezone=Europe/Berlin&lang=fr
velibLocalisationStations: https://opendata.paris.fr/explore/dataset/velib-emplacement-des-stations/download/?format=geojson&timezone=Europe/Berlin&lang=fr

velibCompteursParquet: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/comptage-velo-donnees-compteurs.parquet

contoursDepartements: https://www.data.gouv.fr/fr/datasets/r/eb36371a-761d-44a8-93ec-3d728bec17ce

bpe2023: https://minio.lab.sspcloud.fr/lgaliana/diffusion/BPE23.parquet
dpe: https://koumoul.com/data-fair/api/v1/datasets/dpe-france/lines?format=json&q_mode=simple&qs=code_insee_commune_actualise%3A%2201450%22&size=100&select=%2A&sampling=neighbors

urlReferentielEducation10: https://data.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-annuaire-education/records?where=code_departement%20like%20%22031%22
contoursApiGeo: https://geo.api.gouv.fr/communes/29168?fields=nom,code,codesPostaux,codeDepartement,codeRegion,population&format=geojson&geometry=contour
referentielEducationDataGouv: https://tabular-api.data.gouv.fr/api/resources/b22f04bf-64a8-495d-b8bb-d84dbc4c7983/data/?Code_departement__exact=031
referentielEducationDataGouv200: https://data.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-annuaire-education/records?where=code_departement%20like%20%22031%22&limit=200

openfoodDump: https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv

dvf: https://www.data.gouv.fr/fr/datasets/r/56bde1e9-e214-408b-888d-34c57ff005c4
dvfParquet: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/dvf.parquet

historicalDataUS: https://dataverse.harvard.edu/api/access/datafile/3641280?gbrecs=false

countyLevelResults: https://raw.githubusercontent.com/tonmcg/US_County_Level_Election_Results_08-20/master/2020_US_County_Level_Presidential_Results.csv

emissionsCommunales: https://koumoul.com/s/data-fair/api/v1/datasets/igt-pouvoir-de-rechauffement-global/convert
gpkgLandes: https://minio.lab.sspcloud.fr/projet-formation/diffusion/r-geographie/landes.gpkg

sireneHistory: https://www.data.gouv.fr/fr/datasets/r/0651fb76-bcf3-4f6a-a38d-bc04fa708576
sireneGeoloc: https://files.data.gouv.fr/insee-sirene-geo/GeolocalisationEtablissement_Sirene_pour_etudes_statistiques_utf8.zip


shapefileUS:
  - raw: https://www2.census.gov/geo/tiger/GENZ2019/shp/cb_2019_us_county_20m.zip
  - backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/shapefile_county_us_2019.zip

shapefileUS: https://www2.census.gov/geo/tiger/GENZ2019/shp/cb_2019_02_sldl_500k.zip

autoEcole: https://www.data.gouv.fr/fr/datasets/r/d4b6b072-8a7d-4e04-a029-8cdbdbaf36a5
