# MANIPULATION --------------------------------------------------------------

cog2023:
  raw: https://www.insee.fr/fr/statistiques/fichier/6800675/v_commune_2023.csv
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/cog_2023.csv


codePostaux:
  raw: https://datanova.laposte.fr/data-fair/api/v1/datasets/laposte-hexasmal/raw
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/code-postal.csv

bpe2023:
  raw: https://minio.lab.sspcloud.fr/lgaliana/diffusion/BPE23.parquet
  backup: https://minio.lab.sspcloud.fr/lgaliana/diffusion/BPE23.parquet

gpkgLandes:
  raw: https://minio.lab.sspcloud.fr/projet-formation/diffusion/r-geographie/landes.gpkg
  backup: https://minio.lab.sspcloud.fr/projet-formation/diffusion/r-geographie/landes.gpkg


# CHAPITRE API =========================

openfoodDump:
  raw: https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/openfood.csv # does not exist yet


britishLibraryBooks:
  raw: https://raw.githubusercontent.com/realpython/python-data-cleaning/master/Datasets/BL-Flickr-Images-Book.csv
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/british-library.csv # does not exist yet


autoEcole:
  raw: https://www.data.gouv.fr/fr/datasets/r/d4b6b072-8a7d-4e04-a029-8cdbdbaf36a5
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/autoecole.xls # does not exist yet

dpe:
  raw: https://koumoul.com/data-fair/api/v1/datasets/dpe-france/lines?format=json&q_mode=simple&qs=code_insee_commune_actualise%3A%2201450%22&size=100&select=%2A&sampling=neighbors
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/dpe.json # does not exist yet


emissionsCommunales:
  raw: https://koumoul.com/s/data-fair/api/v1/datasets/igt-pouvoir-de-rechauffement-global/convert
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/emissions.csv # does not exist yet


# urlReferentielEducation10: https://data.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-annuaire-education/records?where=code_departement%20like%20%22031%22
# contoursApiGeo: https://geo.api.gouv.fr/communes/29168?fields=nom,code,codesPostaux,codeDepartement,codeRegion,population&format=geojson&geometry=contour
# referentielEducationDataGouv: https://tabular-api.data.gouv.fr/api/resources/b22f04bf-64a8-495d-b8bb-d84dbc4c7983/data/?Code_departement__exact=031
# referentielEducationDataGouv200: https://data.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-annuaire-education/records?where=code_departement%20like%20%22031%22&limit=200


# VISUALISATION ----------------------------------------

velibHistoricalParquet:
  raw: https://opendata.paris.fr/api/explore/v2.1/catalog/datasets/comptage-velo-donnees-compteurs/exports/parquet?lang=fr&timezone=Europe%2FParis
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/velib-historical.parquet # does not exist yet

velibComptageVelo:
  raw: https://opendata.paris.fr/explore/dataset/comptage-velo-donnees-compteurs/dataviz/?disjunctive.id_compteur&disjunctive.nom_compteur&disjunctive.id&disjunctive.name
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/velib-comptage.parquet # does not exist yet

velibEmplacementStations:
  raw: https://opendata.paris.fr/explore/dataset/velib-emplacement-des-stations/download/?format=geojson&timezone=Europe/Berlin&lang=fr
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/velib-emplacement-stations.parquet # does not exist yet

velibCompteursParquet:
  raw: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/comptage-velo-donnees-compteurs.parquet
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/comptage-velo-donnees-compteurs.parquet


# NLP -----------------------------------------------------------------------

spooky:
  raw: https://github.com/GU4243-ADS/spring2018-project1-ginnyqg/blob/master/data/spooky.csv
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/spooky.csv # does not exist yet

MonteCristo:
  raw: https://www.gutenberg.org/files/17989/17989-0.txt
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/dumas.txt # does not exist yet


# MODERN -------------------------------------------------------------------

contoursDepartements:
  raw: https://www.data.gouv.fr/fr/datasets/r/eb36371a-761d-44a8-93ec-3d728bec17ce
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/departements-20180101-shp.zip # does not exist yet

sireneHistory:
  raw: https://www.data.gouv.fr/fr/datasets/r/0651fb76-bcf3-4f6a-a38d-bc04fa708576
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/stockEtablissement.zip # does not exist yet

sireneGeoloc:
  raw: https://files.data.gouv.fr/insee-sirene-geo/GeolocalisationEtablissement_Sirene_pour_etudes_statistiques_utf8.zip
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/stockEtablissement_geoloc.zip # does not exist yet


# MODELISATION ----------------------------

countyResults:
  raw: https://raw.githubusercontent.com/tonmcg/US_County_Level_Election_Results_08-20/master/2020_US_County_Level_Presidential_Results.csv
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/countyresults.csv # does not exist yet


historicalDataUS:
  raw: https://dataverse.harvard.edu/api/access/datafile/3641280?gbrecs=false
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/historical.tab # does not exist yet

shapefileUS:
  - raw: https://www2.census.gov/geo/tiger/GENZ2019/shp/cb_2019_us_county_20m.zip
  - backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/shapefile_county_us_2019.zip

shapefileUSbis:
  raw: https://www2.census.gov/geo/tiger/GENZ2019/shp/cb_2019_02_sldl_500k.zip
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/shapefile_county_us_2019_500k.zip # does not exist yet


dvf:
  raw: https://www.data.gouv.fr/fr/datasets/r/56bde1e9-e214-408b-888d-34c57ff005c4
  backup: https://minio.lab.sspcloud.fr/lgaliana/data/python-ENSAE/dvf.parquet






