:::: {.content-visible when-profile="fr"}
Voici les citations, ici en vrac, pour pouvoir démarrer. 

Dans cette cellule, créer la structure de données adéquates pour cet exercice.
::::

:::: {.content-visible when-profile="en"}
Here are the quotes, in bulk, to get you started. 

In this cell, create the appropriate data structure for this exercise.
::::


```{pyodide}
#| echo: true
#| exercise: ex_1

citations = ________

# A partir de ces citations

"Rien ne sert de courir ; il faut partir à point."
"Selon que vous serez puissant ou misérable, les jugements de cour vous rendront blanc ou noir."
"Heureux qui comme Ulysse a fait bon voyage"
"L'homme est né libre, et partout il est dans les fers."
"La première fois qu'Aurélien vit Bérénice, il la trouva franchement laide"
"Aujourd'hui maman est morte. Ou peut-être hier, je ne sais pas."
```

::::: {.content-visible when-profile="fr"}
:::: {.hint exercise="ex_1"}
::: {.callout-note collapse="false"}
## Indice 1

Quelle structure de données pourrait permettre d'avoir ce type de code ?

```python
citations.get("La Fontaine")
```
:::
::::
:::::

::::: {.content-visible when-profile="en"}
:::: {.hint exercise="ex_1"}
::: {.callout-note collapse="false"}
## Hint 1

What data structure would enable this type of code?

```python
citations.get("La Fontaine")
```

:::
::::
:::::

::::: {.content-visible when-profile="fr"}
:::: {.hint exercise="ex_1"}
::: {.callout-note collapse="false"}
## Indice 2

Quelle structure de données pourrait permettre d'avoir un objet ressemblant à

```{ojs}
citations
```

:::
::::
:::::

::::: {.content-visible when-profile="en"}
:::: { .hint exercise="ex_1"}
::: { .callout-note collapse="false"}
## Hint 2

What data structure could make an object look like

```{ojs}
citations
```

:::
::::
:::::

::::: {.content-visible when-profile="fr"}
:::: {.hint exercise="ex_1"}
::: {.callout-note collapse="false"}
## Indice 3

Un dictionnaire pourrait vous aider. Si vous avez encore du mal à comprendre pourquoi et comment, retournez au _notebook_ dédié ⬆️.

:::
::::
:::::

::::: {.content-visible when-profile="fr"}
:::: {.hint exercise="ex_1"}
::: {.callout-note collapse="false"}
## Hint 3

A dictionary may help. If you are still struggling to understand why and how, go back to the dedicated _notebook_ ⬆️.

:::
::::
:::::

```{python}
citations = {
  "La Fontaine": [
    "Rien ne sert de courir ; il faut partir à point.",
    "Selon que vous serez puissant ou misérable, les jugements de cour vous rendront blanc ou noir."
  ],
  "Du Bellay": [
    "Heureux qui comme Ulysse a fait bon voyage"
  ],
  "Rousseau": [
    "L'homme est né libre, et partout il est dans les fers."
  ],
  "Aragon": [
    "La première fois qu'Aurélien vit Bérénice, il la trouva franchement laide"
  ],
  "Camus": [
    "Aujourd'hui maman est morte. Ou peut-être hier, je ne sais pas."
  ],
}
```

```{python}
ojs_define(citations = citations)
```


::::: {.content-visible when-profile="fr"}
Pour la question 1, vous pouvez utiliser cette cellule. 
:::::

::::: {.content-visible when-profile="en"}
For question 1, you can use this cell. 
:::::

```{pyodide}
#| exercise: ex_1_q1
# Tester ici votre réponse à la question 1
```


```{python}
def citations_auteur(citations: dict, auteur: str = "Camus"):
  return citations.get(auteur)

citation_aragon = citations_auteur(citations, "Aragon")
```

::::: {.content-visible when-profile="fr"}
Pour la question 2, vous pouvez utiliser cette cellule. 
:::::

::::: {.content-visible when-profile="en"}
For question 2, you can use this cell. 
:::::

```{pyodide}
#| exercise: ex_1_q2
stats_phrases = ___
```

```{python}
stats_phrases = {}

for auteur, liste_citations in citations.items():
  stats_phrases[auteur] = {
    "longueur": [len(c.split()) for c in liste_citations],
    "unique": [len(set(c.split())) for c in liste_citations],
  }
  
```

::::: {.content-visible when-profile="fr"}
:::: {.hint exercise="ex_1_q2"}
::: {.callout-note collapse="false"}
## Indice 1

Comment itérer sur les clés et valeurs de votre dict `stats_phrases` ?

:::
::::
:::::

::::: {.content-visible when-profile="en"}
:::: {.hint exercise="ex_1_q2"}
::: {.callout-note collapse="false"}
## Hint 1

How do you iterate over the keys and values of your `stats_phrases` dict?

:::
::::
:::::

::::: {.content-visible when-profile="fr"}
:::: {.hint exercise="ex_1_q2"}
::: {.callout-note collapse="false"}
## Indice 2

Adopter cette structure générale :

```{.python}
for auteur, liste_citations in citations.items():
    # do something
```

Comment avoir la longueur d'une phrase (suite de mots) et des mots uniques dans celle-ci ?

:::
::::
:::::

::::: {.content-visible when-profile="en"}
:::: {.hint exercise="ex_1_q2"}
::: {.callout-note collapse="false"}
## Hint 2

Adopt this general structure :

```{.python}
for auteur, liste_citations in citations.items():
    # do something
```

How to have the length of a sentence (sequence of words) and single words in it?

:::
::::
:::::

::::: {.content-visible when-profile="fr"}
:::: {.hint exercise="ex_1_q2"}
::: {.callout-note collapse="false"}
## Indice 3

Comment avoir la longueur d'une phrase (suite de mots) et des mots uniques dans celle-ci ?

1. Une phrase (chaîne de caractères) peut être décomposée en mots (liste) avec la méthode `split()`
2. Un `set` permet de dédoublonner une liste

:::
::::
:::::

::::: {.content-visible when-profile="en"}
:::: {.hint exercise="ex_1_q2"}
::: {.callout-note collapse="false"}
## Hint 3

How can I get the length of a sentence (sequence of words) and the single words in it?

1. A sentence (string) can be broken down into words (list) using the `split()` method.
2. A `set` can be used to deduplicate a list

:::
::::
:::::


::::: {.content-visible when-profile="fr"}
:::: {.hint exercise="ex_1_q2"}
::: {.callout-note collapse="false"}
## Indice 4

Vous devriez obtenir ce type de résultat:

```{ojs}
stats_phrases
```

:::
::::
:::::

::::: {.content-visible when-profile="en"}
:::: {.hint exercise="ex_1_q2"}
::: {.callout-note collapse="false"}
## Hint 4

You should get this type of result:

```{ojs}
stats_phrases
```

:::
::::
:::::

```{python}
ojs_define(stats_phrases = stats_phrases)
```

::::: {.content-visible when-profile="fr"}
::: {.callout-warning}
Idéalement, il faudrait faire attention à la ponctuation. 

Mais nous n'avons pas encore appris comment faire des substitutions raffinées dans des chaînes de caractères, cela sera dans un prochain chapitre.
:::
:::::

::::: {.content-visible when-profile="en"}
::: {.callout-warning}
Ideally, you should pay attention to punctuation. 

But we have not yet learned how to make refined substitutions in strings - that will come in another chapter.
:::
:::::