:::: {.content-visible when-profile="fr"}

::: {.callout-tip}
## Exercice 1

Vous disposez d'une liste de citations issues d'oeuvres littéraires de notre magnifique patrimoine littéraire :

  <details>
  <summary>
  Voir la liste de citations qui seront utiles
  </summary>

  | Citation | Auteur |
  |---------|----------|
  | "Rien ne sert de courir ; il faut partir à point." | La Fontaine |
  | "Selon que vous serez puissant ou misérable, les jugements de cour vous rendront blanc ou noir." | La Fontaine |
  | "Heureux qui comme Ulysse a fait bon voyage" | Du Bellay |
  | "L'homme est né libre, et partout il est dans les fers." | Rousseau |
  | "Parce que c'était lui, parce que c'était moi." | Montaigne |
  | "La première fois qu'Aurélien vit Bérénice, il la trouva franchement laide" | Aragon |
  | "Aujourd'hui maman est morte. Ou peut-être hier, je ne sais pas." | Camus |

  </details>

Créer un objet `citations` qui utilise une structure de données adéquate en `Python` pour:

1. Pouvoir facilement retrouver toutes les citations associées à un auteur. Créer un objet `citation_aragon` qui teste la validité de votre approche avec l'exemple d'Aragon. 
2. Pour chaque citation, compter le nombre de mots et le nombre de mots uniques. Créer un objet `stats_phrases` qui liste ces propriétés. Tester sur les citations de la Fontaine.

:::

::::

:::: {.content-visible when-profile="en"}

::: {.callout-tip}
## Exercice 1

You have at your disposal a list of quotations from the magnificent French literary heritage:

<details>
<summary>
See the list of quotations that will be useful
</summary>

| Citation | Auteur |
|---------|----------|
| "Rien ne sert de courir ; il faut partir à point." | La Fontaine |
| "Selon que vous serez puissant ou misérable, les jugements de cour vous rendront blanc ou noir." | La Fontaine |
| "Heureux qui comme Ulysse a fait bon voyage" | Du Bellay |
| "L'homme est né libre, et partout il est dans les fers." | Rousseau |
| "Parce que c'était lui, parce que c'était moi." | Montaigne |
| "La première fois qu'Aurélien vit Bérénice, il la trouva franchement laide" | Aragon |
| "Aujourd'hui maman est morte. Ou peut-être hier, je ne sais pas." | Camus |

</details>

Create a `citations` object that uses a suitable data structure in `Python` to:

1. Easily retrieve all quotations associated with an author. Create a `citation_aragon` object that tests the validity of your approach with the Aragon example. 
2. For each quotation, count the number of words and the number of unique words. Create a `stats_phrases` object that lists these properties. Test on La Fontaine quotations.

:::


::::