::: {.content-visible when-profile="fr"}
## Exercice 3: les chaînes de caractères

Voici le type de motif final vers lequel vous désirez aboutir à la question 1 et 2. 

```
On 17 March 2022, Nadia (34) reported an income of $33,333.33.
```
:::

::: {.content-visible when-profile="en"}
## Exercise 3: strings

This is the final pattern you should end up in question 1 and 2

```
On 17 March 2022, Nadia (34) reported an income of $33,333.33.
```
:::

:::: {.content-visible when-profile="fr"}

::: {.callout-tip}
## Exercice 3

1. A partir de la méthode `format`, essayez d'obtenir le résultat attendu.
2. Faites de même avec les _f-strings_.
3. Modifiez le message pour créer un revenu mensuel arrondi à 1 chiffre. Utiliser l'espace comme séparateur de milliers plutôt que le séparateur par défaut (la virgule).
4. Voici un chemin fictif `C:\Users\Nadia\Documents\cours\chapitre_03\notes.txt` vers un fichier. Faire un _print_ correctif de celui-ci.  
:::

::::

:::: {.content-visible when-profile="en"}
## Exercise 3

1. Using the `format` method, try to obtain the expected result.
2. Do the same with _f-strings_.
3. Modify the message to create a monthly income rounded to 1 digit. Use a space as the thousands separator rather than the default separator (the comma).
4. Here is a fictitious path `C:\Users\Nadia\Documents\cours\chapitre_03\notes.txt` to a file. Make a correct print of it.  
::::

::: {.content-visible when-format="html"}

```{pyodide}
#| autorun: true
import datetime

date = datetime.datetime(2022, 3, 17)
prenom = "Nadia"
age = 34
revenu = 100000/3
```

:::

```{python}
import datetime

date = datetime.datetime(2022, 3, 17)
prenom = "Nadia"
age = 34
revenu = 100000/3
```

:::: {.content-visible when-profile="fr"}
Dans la première partie de cet exercice, vous devriez avoir ces résultats. 
::::

:::: {.content-visible when-profile="en"}
In the first part of this exercise, you should have these results. 
::::

```{python}
# Question 1
msg_format = "On {date:%d %B %Y}, {prenom} ({age}) reported an income of ${revenu:,.2f}.".format(
    date=date, prenom=prenom, age=age, revenu=revenu
)

print("Question 1:")
print(msg_format)

# Question 2
msg_fstring = f"On {date:%d %B %Y}, {prenom} ({age}) reported an income of ${revenu:,.2f}."

print("Question 2:")
print(msg_fstring)

# Question 3
msg_fstring = f"On {date:%d %B %Y}, {prenom} ({age}) reported an income of ${revenu/12:,.1f}.".replace(',', ' ')

print("Question 3:")
print(msg_fstring)
```

::: {.content-visible when-format="html"}

:::: {.content-visible when-profile="fr"}
Vous pouvez tester ci-dessous votre solution
::::

:::: {.content-visible when-profile="en"}
Try replicating these results using interactive cell below 
::::

```{pyodide}
# Try here
```

:::

:::: {.content-visible when-profile="fr"}
Dans la deuxième partie de l'exercice, si vous utilisez le mauvais type de _string_, vous devriez avoir une erreur:
::::

:::: {.content-visible when-profile="en"}
In the second part of the exercise, if you use the wrong type of _string_, you should get an error:
::::


::: {.content-visible when-format="html"}

```{pyodide}
# Question 4: start from
"C:\Users\Nadia\Documents\cours\chapitre_03\notes.txt"
```

:::

```{python}
#| error: true
# Question 4
chemin_bad = "C:\Users\Nadia\Documents\cours\chapitre_03\notes.txt"

print(chemin_bad)
```

:::: {.content-visible when-profile="fr"}
Les slashs posent souvent problème. Avec des _raw strings_ vous ne devriez pas rencontrer ce problème:
::::

:::: {.content-visible when-profile="en"}
Slashes often cause problems. With raw strings, you should not encounter this problem:
::::


```{python}
# Question 4
chemin_ok = r"C:\Users\Nadia\Documents\cours\chapitre_03\notes.txt"
print(f"File can be found here: {chemin_ok}")

# This alternative is ok
chemin_ok2 = "C:\\Users\\Nadia\\Documents\\cours\\chapitre_03\\notes.txt"
```
