::: {.content-visible when-profile="fr"}

:::: {#tip-empreinte-carbone .callout-tip}
## Calculer l'empreinte carbone par habitant

En premier lieu, on va calculer l'empreinte carbone de chaque commune. 


1. Créer une variable `emissions` qui correspond aux émissions totales d'une commune

2. Faire une jointure à gauche entre les données d'émissions et les données de cadrage[^notebiais].

3. Calculer l'empreinte carbone (émissions totales / population). 

A ce stade nous pourrions avoir envie d'aller vers la modélisation pour essayer d'expliquer
les déterminants de l'empreinte carbone à partir de variables communales. 
Une approche inférentielle nécessite néanmoins pour être pertinente de
vérifier en amont des statistiques descriptives.

4. Sortir un histogramme en niveau puis en log de l'empreinte carbone communale.

5. Regarder la corrélation entre les variables de cadrage et l'empreinte carbone. Certaines variables semblent-elles pouvoir potentiellement influer sur l'empreinte carbone ?

::::

:::

::: {.content-visible when-profile="en"}

:::: {#tip-empreinte-carbone-en .callout-tip}
## Calculate the carbon footprint per capita

First, we will calculate the carbon footprint of each commune.

1. Create a variable `emissions` that corresponds to the total emissions of a commune.

2. Perform a left join between the emissions data and the framing data[^notebiais].

3. Calculate the carbon footprint (total emissions / population).

At this stage, we might want to move towards modeling to try to explain the determinants of the carbon footprint based on communal variables. However, for an inferential approach to be relevant, it is necessary to check some descriptive statistics beforehand.

4. Generate a histogram of the carbon footprint per commune in level and log.

5. Look at the correlation between the framing variables and the carbon footprint. Do some variables seem to potentially influence the carbon footprint?

::::

:::
