::: {.content-visible when-profile="fr"}

:::: {.callout-tip}
## Exercice 1 : Exploiter l'API DVF

1. Rechercher toutes les transactions existantes dans DVF à Plogoff (code commune `29168`, en Bretagne).
Afficher les clés du JSON et en déduire le nombre de transactions répertoriées. 
2. N'afficher que les transactions portant sur des maisons. 
3. Utiliser l'[API geo](https://api.gouv.fr/documentation/api-geo) pour
récupérer le découpage communal de la ville de Plogoff.
4. Représenter l'histogramme des prix de vente.

N'hésitez pas à aller plus loin en jouant sur des variables de
groupes par exemple.

::::

:::

::: {.content-visible when-profile="en"}

:::: {.callout-tip}
## Exercise 1: Using the DVF API

1. Search for all existing transactions in DVF at Plogoff (municipality code `29168`, in Brittany).
Display the keys of the JSON and deduce the number of recorded transactions.
2. Display only the transactions concerning houses.
3. Use the [API geo](https://api.gouv.fr/documentation/api-geo) to retrieve the municipal boundaries of the city of Plogoff.
4. Plot the histogram of sales prices.

Feel free to go further by playing with group variables, for example.

::::

:::


