:::: {.content-visible when-profile="fr"}

::: {.callout-tip}
## Exercice 3: une requête `POST` pour géolocaliser en masse nos données

1. Enregistrer au format CSV les colonnes `adresse`, `DEPCOM` et `Nom_commune` de la base d'équipements fusionnée avec notre répertoire précédent (objet `bpe_enriched`). Il peut être utile, avant l'écriture au format CSV, de remplacer les virgules dans la colonne `adresse` par des espaces.
2. Créer l'objet `response` avec `requests.post` et les bons arguments pour géocoder votre CSV.
3. Transformer votre output en objet `geopandas` avec la commande suivante:

```{.python}
bpe_loc = pd.read_csv(io.StringIO(response.text))
```

:::

::::

:::: {.content-visible when-profile="en"}

::: {.callout-tip}
## Exercise 3: A `POST` request to geolocate our data in bulk

1. Save the `adresse`, `DEPCOM`, and `Nom_commune` columns of the equipment database merged with our previous directory (object `bpe_enriched`) in CSV format. Before writing to CSV, it may be helpful to replace commas in the `adresse` column with spaces.
2. Create the `response` object using `requests.post` with the correct arguments to geocode your CSV.
3. Transform your output into a `geopandas` object using the following command:

```{.python}
bpe_loc = pd.read_csv(io.StringIO(response.text))
```

:::

::::
