::: {.content-visible when-profile="fr"}

:::: {.exercise}
## Exercice 2 : Quelles sont les auto-écoles les plus proches de chez moi ?

On va supposer que vous cherchez, dans un rayon donné autour d'un centre ville,
les auto-écoles disponibles.

<details>
<summary>
Fonction nécessaire pour cet exercice
</summary>
Cet exercice nécessite une fonction pour créer un cercle
autour d'un point
(source [ici](https://gis.stackexchange.com/questions/289044/creating-buffer-circle-x-kilometers-from-point-using-python/289923)).
La voici :

```python
from functools import partial
import pyproj
from shapely.ops import transform
from shapely.geometry import Point

proj_wgs84 = pyproj.Proj('+proj=longlat +datum=WGS84')


def geodesic_point_buffer(lat, lon, km):
    # Azimuthal equidistant projection
    aeqd_proj = '+proj=aeqd +lat_0={lat} +lon_0={lon} +x_0=0 +y_0=0'
    project = partial(
        pyproj.transform,
        pyproj.Proj(aeqd_proj.format(lat=lat, lon=lon)),
        proj_wgs84)
    buf = Point(0, 0).buffer(km * 1000)  # distance in metres
    return transform(project, buf).exterior.coords[:]
```
</details>


1. Pour commencer, utiliser l'[API Geo](https://geo.api.gouv.fr/decoupage-administratif)
pour la ville de Palaiseau.
2. Appliquer la fonction `geodesic_point_buffer` au centre ville de Palaiseau
3. Ne conserver que les auto-écoles dans ce cercle et les ordonner 

__Si vous avez la réponse à la question 3, n'hésitez pas à la soumettre sur `Github` afin que je complète la correction__ 😉 !

::::

:::


::: {.content-visible when-profile="en"}

:::: {.exercise}
## Exercise 2: Which driving schools are closest to my home?

Let's assume you are looking, within a given radius around a city center, for available driving schools.

<details>
<summary>
Function needed for this exercise
</summary>
This exercise requires a function to create a circle around a point (source [here](https://gis.stackexchange.com/questions/289044/creating-buffer-circle-x-kilometers-from-point-using-python/289923)). Here it is:

```python
from functools import partial
import pyproj
from shapely.ops import transform
from shapely.geometry import Point

proj_wgs84 = pyproj.Proj('+proj=longlat +datum=WGS84')

def geodesic_point_buffer(lat, lon, km):
    # Azimuthal equidistant projection
    aeqd_proj = '+proj=aeqd +lat_0={lat} +lon_0={lon} +x_0=0 +y_0=0'
    project = partial(
        pyproj.transform,
        pyproj.Proj(aeqd_proj.format(lat=lat, lon=lon)),
        proj_wgs84)
    buf = Point(0, 0).buffer(km * 1000)  # distance in metres
    return transform(project, buf).exterior.coords[:]
```
</details>

1. To begin, use the [Geo API](https://geo.api.gouv.fr/decoupage-administratif) for the city of Palaiseau.
2. Apply the `geodesic_point_buffer` function to the center of Palaiseau.
3. Keep only the driving schools within this circle and order them.

__If you have the answer to question 3, feel free to submit it on `GitHub` so I can complete the correction__ 😉 !

::::

:::
