::::: {.content-visible when-profile="fr"}

:::: {.callout-tip}
## Exercice 4 : API authentifiée par le biais du navigateur

1. Se créer un compte sur le [portail des API](https://api.insee.fr/catalogue/)
2. Aller voir l'espace `Mes applications` et en créer une nouvelle. Par simplicité, vous pouvez la nommer _"Python data science"_. Au cours de la création de cette application, souscrire à l'API Sirene. 
3. Cliquer sur l'onglet _Souscriptions_. Choisir l'API Sirene qui devrait normalement être disponible dans le bas de la page.
4. A droite, vous devriez maintenant voir s'afficher un jeton. Gardez cette page ouverte et ouvrez dans un nouvel onglet [portail-api.insee.fr/catalog/all](https://portail-api.insee.fr/catalog/all).

Testons maintenant l'API Sirene grâce au _swagger_ en partant de [portail-api.insee.fr/catalog/all](https://portail-api.insee.fr/catalog/all)

1. Cliquer sur l'onglet `Documentation`. La documentation interactive (le _swagger_) doit maintenant s'afficher. 
2. Plus bas, dans la documentation interactive se rendre au point d'entrée `/siren/{siren}` (méthode `GET`).
3. Cliquer sur le bouton `Try it out` pour essayer l'exemple de manière interactive. 
4. Remplir le champ `siren` avec le SIREN `500569405` qui est l'identificant de Décathlon 😉

Si vous avez l'erreur ci-dessous, comprenez-vous pourquoi ?

```{ojs}
//| echo: false
error_request_no_token
```


Il va falloir être authentifié.

1. Pour cela, recharger cette documentation interactive et cliquer sur le bouton `Authorize`. Dans le _popup_ qui s'affiche, renseigner le jeton issu de l'autre fenêtre. 
2. Après avoir validé ce jeton, retentez la procédure précédente de récupération des informations de Décathlon. 

Vous devriez maintenant avoir cette sortie :

```{ojs}
//| echo: false
sortie_sirene_decathlon
```

::::

:::::


::::: {.content-visible when-profile="en"}

:::: {.callout-tip}
## Exercise 4: API authenticated through the browser

1. Create an account on Insee [API portal](https://api.insee.fr/catalogue/) (seems to be only in French, sorry about that).
2. Go to the `My Applications` section and create a new one. For simplicity, you can name it `Python data science`. While creating this application, subscribe to the Sirene API. 
3. Click on the Subscriptions tab. Select the Sirene API, which should normally be available at the bottom of the page.
4. On the right, you should now see a token displayed. Keep this page open and open [portail-api.insee.fr/catalog/all](https://portail-api.insee.fr/catalog/all) in a new tab.

Now let's test the Sirene API using _swagger_, starting from [portail-api.insee.fr/catalog/all](https://portail-api.insee.fr/catalog/all).


1. Click on the `Documentation` tab. The interactive documentation (the _swagger_) should now be displayed. 
2. Further down in the interactive documentation, go to the entry point `/siren/{siren}` (`GET` method).
3. Click on the `Try it out` button to try out the example interactively.
4. Fill in the `siren` field with the SIREN `500569405`, which is Decathlon's identifier 😉
If you get the error below, do you understand why?

```{ojs}
//| echo: false
error_request_no_token
```

You will need to be authenticated.

1. To do this, reload this interactive documentation and click on the `Authorise` button. In the pop-up that appears, enter the token from the other window.
2. After validating this token, try the previous procedure for retrieving information from Decathlon again.

You should now see this output:

```{ojs}
//| echo: false
sortie_sirene_decathlon
```

::::

:::::


