::: {.content-visible when-profile="fr"}

## Récupération des données via `Python` {{< fa brands python >}}


Pour cette application, à partir de la question 4, nous allons avoir besoin de créer une classe spéciale permettant à `requests` de surcharger notre requête d'un jeton d'authentification. Comme elle n'est pas triviale à créer sans connaissance préalable, la voici:
:::

::: {.content-visible when-profile="en"}

## Application

For this application, starting from question 4, we will need to create a special class that allows `requests` to override our request with an authentication token. Since it is not trivial to create without prior knowledge, here it is:
:::

```{python}
#| echo: true
#| label: bearer-token
class BearerAuth(requests.auth.AuthBase):
    def __init__(self, token):
        self.token = token
    def __call__(self, r):
        r.headers["X-INSEE-Api-Key-Integration"] = self.token
        return r
```

```{python}
#| echo: true
siren = "500569405"
```


::: {.content-visible when-profile="fr"}

:::: {.callout-tip}
## Exercice 5 : les tokens avec `Python` {.unnumbered}

1. Créer une variable `token` par le biais de `getpass`.
2. Utiliser cette structure de code pour récupérer la donnée voulue

```{.python}
requests.get(
    url,
    auth=BearerAuth(token)
)
```

3. Remplacer l'utilisation de `getpass` par l'approche variable d'environnement grâce à [`dotenv`](https://pypi.org/project/python-dotenv/).
::::

:::


::: {.content-visible when-profile="en"}

:::: {.callout-tip}
## Exercice 5 : API tokens with `Python` {.unnumbered}

1. Create a `token` variable using `getpass`.
2. Use this code structure to retrieve the desired data.

```{.python}
requests.get(
    url,
    auth=BearerAuth(token)
)
```

3. Replace `getpass` snippet with the environment variable approach using [`dotenv`](https://pypi.org/project/python-dotenv/).
::::

:::
