::: {.content-visible when-profile="fr"}
# Première utilisation d'API

Une API a donc vocation à servir d'intermédiaire entre un client et un serveur. Ce client peut être de deux types: une interface web ou un logiciel de programmation. L'API ne fait pas d'_a priori_ sur l'outil qui sert lui passe une commande, elle lui demande seulement de respecter un standard (en général une requête http), une structure de requête (les arguments) et d'attendre le résultat.

## Comprendre le principe avec un exemple interactif

Le premier mode (accès par un navigateur) est principalement utilisé lorsqu'une interface web permet à un utilisateur de faire des choix afin de lui renvoyer des résultats correspondant à ceux-ci. Prenons à nouveau l'exemple de l'API de géolocalisation que nous utiliserons dans ce chapitre. Imaginons une interface web permettant à l'utilisateur deux choix: un code postal et une adresse. Cela sera injecté dans la requête et le serveur répondra avec la géolocalisation adaptée.
:::

::: {.content-visible when-profile="en"}

# APIs 101

APIs intends to serve as an intermediary between a client and a server. This client can be of two types: a web interface or programming software. The API makes no assumptions about the tool sending it a command; it simply requires adherence to a standard (usually an HTTP request), a query structure (the arguments), and then awaits the result.

## Understanding with an interactive example

The first mode (access via a browser) is primarily used when a web interface allows a user to make choices in order to return results corresponding to those selections. Let's revisit the example of the geolocation API that we will use in this chapter. Imagine a web interface that offers the user two choices: a postal code and an address. These inputs will be injected into the query, and the server will respond with the appropriate geolocation.
:::


::::: {.content-visible when-profile="fr"}

:::: {.content-visible when-format="ipynb"}

::: {.callout-important}
Une explication interactive est disponible sur [le site du cours](https://pythonds.linogaliana.fr/content/manipulation/04c_API_TP.html).
:::

::::

:::::

::::: {.content-visible when-format="ipynb"}

:::: {.content-visible when-profile="en"}

::: {.callout-important}
An interactive explanation is available on [the course website](https://pythonds.linogaliana.fr/content/manipulation/04c_API_TP.html).
:::

::::

:::::


::::: {.content-visible when-format="html"}

:::: {.content-visible when-profile="fr"}

Voici donc nos deux _widgets_ pour permettre au client (l'utilisateur de la page web) de choisir son adresse.

```{ojs}
//| label: viewer-interactive-example1-fr
html`
<div class="widget-code-postal">${viewof codePostal}</div>
<div class="widget-address">${viewof adresse}</div>
`
```

```{ojs}
html`
<div class="map-example">${map}</div>
`
```


Une petite mise en forme des valeurs renseignées par ce _widget_ permet d'obtenir la requête voulue:

```{ojs}
//| label: text-formatting-fr
md`${textFormattingAPI}`
```

Ce qui nous donne un output au format JSON, le format de sortie d'API le plus commun.

::::

::: {.content-visible when-profile="en"}

Here are our two _widgets_ that allow the client (the web page user) to choose their address.

```{ojs}
//| label: viewer-interactive-example1-en
html`
<div class="widget-code-postal">${viewof codePostal}</div>
<div class="widget-address">${viewof adresse}</div>
`
```

```{ojs}
html`
<div class="map-example">${map}</div>
`
```


A little formatting of the values provided by this widget allows one to obtain the desired query:

```{ojs}
//| label: text-formatting-en
md`${textFormattingAPI}`
```

This gives us an output in JSON format, the most common output format for APIs.

:::

```{ojs}
//| echo: false
localisation
```


::: {.content-visible when-profile="fr"}

```{ojs}
//| label: text-open-fr
html`${textOpenInBrowserfr}`
```

Si on veut un beau rendu, comme la carte ci-dessus, il faudra que le navigateur retravaille cet output, ce qui se fait normalement avec `Javascript`, le langage de programmation embarqué par les navigateurs.
:::

::: {.content-visible when-profile="en"}

```{ojs}
//| label: text-open-en
html`${textOpenInBrowseren}`
```


If a beautiful display is desired, like the map above, the web browser will need to reprocess this output, which is typically done using `Javascript`, the programming language embedded in web browsers.
:::


:::::


:::: {.content-visible when-format="html"}

```{ojs}
//| echo: false
//| label: form-codePostal
//| output: false
viewof codePostal = Inputs.text({value: "92120", placeholder: "92120", label: md`**Code Postal**`})
```

```{ojs}
//| echo: false
//| label: def-adresse-ojs
//| output: false
viewof adresse = Inputs.text({value: defaultAdresse, placeholder: defaultAdresse, label: md`**Adresse**`})
```

```{ojs}
//| echo: false
//| output: false
interactiveExample1 = html`
<div class="map-example">${map}</div>
`
```

```{ojs}
//| echo: false
//| label: formatting-url-api
//| output: false
textFormattingAPI = md`
${
await mj`$$\underbrace{\text{${apiroot}}}_{\text{API root}}/\underbrace{\text{search}}_{\text{API endpoint}}/?\underbrace{\text{${param1}}}_{\text{main parameter}}\&\underbrace{\text{${param2}}}_{\text{additional parameter}}$$`
}
`
```

```{ojs}
//| echo: false
//| label: open-in-browser-fr
//| output: false
textOpenInBrowserfr = html`
 Pour preuve que cette requête est bien fonctionnelle, on peut l'ouvrir dans un navigateur: <a href="${url}" target="_blank" title="Test de url dans un navigateur">
 <i class="fa-solid fa-magnifying-glass"></i></i>
`
```

```{ojs}
//| echo: false
//| label: open-in-browser-en
//| output: false
textOpenInBrowseren = html`
 To demonstrate that this query is fully functional, you can open it in a web browser: <a href="${url}" target="_blank" title="Testing URL in a query">
 <i class="fa-solid fa-magnifying-glass"></i></i>
`
```

::::