::: {.tip}
## Understanding the PageRank Algorithm

`Google` became famous thanks to its `PageRank` algorithm. This algorithm allows, from links between websites, to give an importance score to a website which will be used to evaluate its centrality in a network. The objective of this exercise is to use `Numpy` to implement such an algorithm from an adjacency matrix that links the sites together.

1. Create the following matrix with `numpy`. Call it `M`:

$$
\begin{bmatrix}
0 & 0 & 0 & 0 & 1 \\
0.5 & 0 & 0 & 0 & 0 \\
0.5 & 0 & 0 & 0 & 0 \\
0 & 1 & 0.5 & 0 & 0 \\
0 & 0 & 0.5 & 1 & 0
\end{bmatrix}
$$

2. To visually represent this minimalist web, convert it into a `networkx` object (a library specialized in network analysis) and use the `draw` function of this package.

It is the transpose of the adjacency matrix that allows linking the sites together. For example, site 1 (first column) is referenced by sites 2 and 3. It only references site 5.

3. From the English Wikipedia page of `PageRank`, test on your matrix.

:::