::: {.callout-tip}
## Comprendre le principe de l'algorithme <code>PageRank</code>

`Google` est devenu célèbre grâce à son algorithme `PageRank`. Celui-ci permet, à partir
de liens entre sites _web_, de donner un score d'importance à un site _web_ qui va
être utilisé pour évaluer sa centralité dans un réseau. 
L'objectif de cet exercice est d'utiliser `Numpy` pour mettre en oeuvre un tel
algorithme à partir d'une matrice d'adjacence qui relie les sites entre eux. 

1. Créer la matrice suivante avec `numpy`. L'appeler `M`:

$$
\begin{bmatrix}
0 & 0 & 0 & 0 & 1 \\
0.5 & 0 & 0 & 0 & 0 \\
0.5 & 0 & 0 & 0 & 0 \\
0 & 1 & 0.5 & 0 & 0 \\
0 & 0 & 0.5 & 1 & 0
\end{bmatrix}
$$

2. Pour représenter visuellement ce _web_ minimaliste,
convertir en objet `networkx` (une librairie spécialisée
dans l'analyse de réseau) et utiliser la fonction `draw`
de ce package. 

Il s'agit de la transposée de la matrice d'adjacence
qui permet de relier les sites entre eux. Par exemple, 
le site 1 (première colonne) est référencé par
les sites 2 et 3. Celui-ci ne référence que le site 5. 

3. A partir de la page wikipedia anglaise de `PageRank`, tester
sur votre matrice. 

:::
