::: {.content-visible when-profile="fr"}

:::: {.exercise}
## Exercice 5 (optionnel): La carte de couverture des stations

Cet exercice est plus complexe parce qu'il implique de revenir à `Shapely`, une librairie plus bas niveau que `GeoPandas`. 

Cet exercice est laissé libre. Une source d'inspiration possible est cette discussion sur [StackExchange](https://gis.stackexchange.com/questions/337561/making-polygon-for-every-point-in-set-using-voronoi-diagram). 

L'objectif est de faire deux cartes de couverture: une au niveau de la petite couronne et l'autre seulement au sein de Paris intramuros. 

::::

:::

::: {.content-visible when-profile="en"}

::: {.exercise}
## Exercise 5 (optional): Coverage map of the stations

This exercise is more complex because it involves going back to `Shapely`, a lower-level library than `GeoPandas`.

This exercise is left open-ended. A possible source of inspiration is this discussion on [StackExchange](https://gis.stackexchange.com/questions/337561/making-polygon-for-every-point-in-set-using-voronoi-diagram).

The objective is to make two coverage maps: one at the level of the petite couronne and the other only within Paris intramuros.

:::


:::

