```{python}
#| output: false
#| echo: true
#| label: load-france-data
from cartiflette import carti_download
france = carti_download(
      values = ["France"],
      crs = 4326,
      borders = "REGION",
      vectorfile_format="geojson",
      simplification=50,
      filter_by="FRANCE_ENTIERE",
      source="EXPRESS-COG-CARTO-TERRITOIRE",
      year=2022)
france = france.loc[france['INSEE_REG']>10]
```

::: {.content-visible when-profile="fr"}

:::: {.exercise}
## Exercice 2 : Les projections, représentations et approximations


1. S'amuser à représenter les limites de la France avec plusieurs projections:

- Mercator WGS84 (EPSG: 4326)
- Projection healpix (`+proj=healpix +lon_0=0 +a=1`)
- Projection prévue pour Tahiti (EPSG: 3304)
- Projection Albers prévue pour Etats-Unis (EPSG: 5070)

2. Calculer la superficie en $km^2$
des régions françaises dans les deux systèmes de projection suivants : 
World Mercator WGS84 (EPSG: 3395) et Lambert 93 (EPSG: 2154). Calculer la différence en $km^2$
pour chaque région.

::::
:::

::: {.content-visible when-profile="en"}

:::: {.exercise}
## Exercise 2: Projections, representations, and approximations

1. Experiment with representing the borders of France using several projections:

- Mercator WGS84 (EPSG: 4326)
- Healpix projection (`+proj=healpix +lon_0=0 +a=1`)
- Projection for Tahiti (EPSG: 3304)
- Albers projection for the United States (EPSG: 5070)

2. Calculate the area in $km^2$ of the French regions in the following two projection systems:
World Mercator WGS84 (EPSG: 3395) and Lambert 93 (EPSG: 2154). Calculate the difference in $km^2$ for each region.

::::
:::