::: {.content-visible when-profile="fr"}

:::: {.exercise}
## Exercice 1: découverte des objets géographiques

En premier lieu, on récupère des données géographiques grâce
au _package_ `cartiflette` et à sa fonction `carti_download`.

1. Utiliser
le code sous cet exercice (celui utilisant `carti_download`) pour
télécharger les contours communaux
des départements de la petite couronne (75, 92, 93 et 94)
de manière simplifiée grâce au _package_
`cartiflette`

2. Regarder les premières lignes des données. Identifier la différence avec
un _dataframe_ standard. 

3. Afficher le système de projection (attribut `crs`) de `communes_borders`. Ce dernier contrôle la
transformation de l'espace tridimensionnel terrestre en une surface plane.
Utiliser `to_crs` pour transformer les données en Lambert 93, le 
système officiel (code EPSG 2154). 

4. Afficher les communes des Hauts de Seine (département 92) et utiliser la méthode
`plot`

5. Ne conserver que Paris et réprésenter les frontières sur une carte : quel est le problème pour
une analyse de Paris intramuros?

On remarque rapidement le problème. 
On ne dispose ainsi pas des limites des arrondissements parisiens, ce
qui appauvrit grandement la carte de Paris. 

6. Cette fois, utiliser l'argument `borders="COMMUNE_ARRONDISSEMENT"` pour obtenir
un fonds de carte consolidé des communes avec les arrondissements dans les grandes villes. 
Convertir en Lambert 93. 

::::

:::

::: {.content-visible when-profile="en"}

:::: {.exercise}
## Exercise 1: Discovering spatial objects

First, we will retrieve geographic data using the `cartiflette` package and its `carti_download` function.

1. Use the code below to download administrative borders for the departments of the inner suburbs (75, 92, 93, and 94) in a simplified manner using the `cartiflette` package

2. Look at the first few rows of the data. Identify the difference from a standard dataframe.

3. Display the projection system (attribute `crs`) of `communes_borders`. This controls the transformation of the three-dimensional terrestrial space into a flat surface. Use `to_crs` to transform the data into Lambert 93, the official system (EPSG code 2154).

4. Display the municipalities of Hauts de Seine (department 92) and use the `plot` method.

5. Keep only Paris and plot the borders on a map: what is the problem for an analysis of intramural Paris?

You will quickly notice the problem. We do not have the boundaries of Parisian districts, which greatly impoverishes the map of Paris.

6. This time, use the argument `borders="COMMUNE_ARRONDISSEMENT"` to obtain a consolidated map with the municipalities and districts in large cities. Convert to Lambert 93.

::::

:::
