::: {.exercise}
## Exercice 1: Importer un CSV et explorer la structure de données

1. Importer les données de l'Ademe à l'aide du package `Pandas` et de la commande consacrée pour l'import de csv. Nommer le `DataFrame` obtenu `emissions`[^nomdf].
2. Utiliser les méthodes adéquates afin d'afficher pour les 10 premières valeurs, les 15 dernières et un échantillon aléatoire de 10 valeurs grâce aux méthodes adéquates du _package_ `Pandas`. 
3. Tirer 5 pourcents de l'échantillon sans remise.
4. Ne conserver que les 10 premières lignes et tirer aléatoirement dans celles-ci pour obtenir un DataFrame de 100 données.
5. Faire 100 tirages à partir des 6 premières lignes avec une probabilité de 1/2 pour la première observation et une probabilité uniforme pour les autres.


<details>
<summary>
En cas de blocage à la question 1
</summary>

Lire la documentation de `read_csv` (très bien faite) ou chercher des exemples
en ligne pour découvrir cette fonction.

</details>


:::

[^nomdf]: Par manque d'imagination, on est souvent tenté d'appeler notre
_dataframe_ principal `df` ou `data`. C'est souvent une mauvaise idée puisque
ce nom n'est pas très informatif quand on relit le code quelques semaines
plus tard. L'autodocumentation, approche qui consiste à avoir un code
qui se comprend de lui-même, est une bonne pratique et il est donc recommandé
de donner un nom simple mais efficace pour connaître la nature du _dataset_ en question.