::: {.content-visible when-profile="fr"}

:::: {.cell .markdown}
::::: {.callout-tip}
## Exercice 1: Importer un CSV et explorer la structure de données

1. Importer les données de l'Ademe à l'aide du package `Pandas` et de la commande consacrée pour l'import de csv. Nommer le `DataFrame` obtenu `emissions`[^nomdf-fr].
2. Utiliser les méthodes adéquates afin d'afficher pour les 10 premières valeurs, les 15 dernières et un échantillon aléatoire de 10 valeurs grâce aux méthodes adéquates du _package_ `Pandas`. 
3. Tirer 5 pourcents de l'échantillon sans remise.
4. Ne conserver que les 10 premières lignes et tirer aléatoirement dans celles-ci pour obtenir un DataFrame de 100 données.
5. Faire 100 tirages à partir des 6 premières lignes avec une probabilité de 1/2 pour la première observation et une probabilité uniforme pour les autres.


<details>
<summary>
En cas de blocage à la question 1
</summary>

Lire la documentation de `read_csv` (très bien faite) ou chercher des exemples
en ligne pour découvrir cette fonction.

</details>


:::::

[^nomdf-fr]: Par manque d'imagination, on est souvent tenté d'appeler notre
_dataframe_ principal `df` ou `data`. C'est souvent une mauvaise idée puisque
ce nom n'est pas très informatif quand on relit le code quelques semaines
plus tard. L'autodocumentation, approche qui consiste à avoir un code
qui se comprend de lui-même, est une bonne pratique et il est donc recommandé
de donner un nom simple mais efficace pour connaître la nature du _dataset_ en question.

::::

:::


::: {.content-visible when-profile="en"}

:::: {.cell .markdown}
::::: {.callout-tip}
## Exercise 1: Importing a CSV and Exploring Data Structure

1. Import the data from Ademe using the `Pandas` package and the dedicated command for importing CSVs. Name the obtained `DataFrame` `emissions`[^nomdf-en].
2. Use the appropriate methods to display the first 10 values, the last 15 values, and a random sample of 10 values using the appropriate methods from the `Pandas` package.
3. Draw 5 percent of the sample without replacement.
4. Keep only the first 10 rows and randomly draw from these to obtain a DataFrame of 100 data points.
5. Make 100 draws from the first 6 rows with a probability of 1/2 for the first observation and a uniform probability for the others.

<details>
<summary>
If you get stuck on question 1
</summary>

Read the documentation for `read_csv` (very well done) or look for examples online to discover this function.

</details>

::::


[^nomdf-en]: Due to a lack of imagination, we are often tempted to call our main _dataframe_ `df` or `data`. This is often a bad idea because the name is not very informative when you read the code a few weeks later. Self-documenting code, an approach that consists of having code that is self-explanatory, is a good practice, and it is recommended to give a simple yet effective name to know the nature of the dataset in question.

::::

:::
