::: {.exercise}
## Exercise 1: Importing a CSV and Exploring Data Structure

1. Import the data from Ademe using the `Pandas` package and the dedicated command for importing CSVs. Name the obtained `DataFrame` `emissions`[^nomdf].
2. Use the appropriate methods to display the first 10 values, the last 15 values, and a random sample of 10 values using the appropriate methods from the `Pandas` package.
3. Draw 5 percent of the sample without replacement.
4. Keep only the first 10 rows and randomly draw from these to obtain a DataFrame of 100 data points.
5. Make 100 draws from the first 6 rows with a probability of 1/2 for the first observation and a uniform probability for the others.

<details>
<summary>
If you get stuck on question 1
</summary>

Read the documentation for `read_csv` (very well done) or look for examples online to discover this function.

</details>

:::

[^nomdf]: Due to a lack of imagination, we are often tempted to call our main _dataframe_ `df` or `data`. This is often a bad idea because the name is not very informative when you read the code a few weeks later. Self-documenting code, an approach that consists of having code that is self-explanatory, is a good practice, and it is recommended to give a simple yet effective name to know the nature of the dataset in question.
