# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Documentation"
  url = "docs/"
  weight = 10

[[main]]
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    name = "Manipuler des données"
    url = "/manipulation"
    weight = 2        
    
[[main]]
    name = "Visualiser des données"
    url = "/visualisation"
    weight = 3        

[[main]]
    name = "Modéliser"
    url = "/modelisation"
    weight = 4        

[[main]]
    name = "NLP"
    url = "/NLP"
    weight = 5     

[[main]]
    name = "Git"
    url = "/git"
    weight = 6        

    
[[main]]
    name = "Evaluation"
    url = "/evaluation"
    weight = 7

[[main]]
    name = "Travaux dirigés"
    url = "/listeTP"
    weight = 8
    
[[main]]
    name = "References"
    url = "/references"
    weight = 9

[[main]]
    name = "Github"
    url = "https://github.com/linogaliana/python-datascientist"
    weight = 10
