    {
        "settings": {
            "index": {
                "number_of_replicas": 2,
                "analysis": {
                    "filter": {
                        "french_stemmer": {
                            "type": "stemmer",
                            "language": "light_french"
                        },
                        "french_stop": {
                            "type": "stop",
                            "language": "_french_"
                        }
                    },
                    "analyzer": {
                        "ngram_analyzer": {
                            "filter": "lowercase",
                            "tokenizer": "ngram_tokenizer"
                        },
                        "stem_analyzer": {
                            "filter": [
                                "french_stop",
                                "french_stemmer"
                            ],
                            "tokenizer": "standard"
                        }
                    },
                    "tokenizer": {
                        "ngram_tokenizer": {
                            "type": "ngram",
                            "min_gram": 3,
                            "max_gram": 4,
                            "token_chars": "letter"
                        }
                    }
                }
            }
        },
        "mappings": {
            "properties": {
                "product_name": {
                    "type": "text",
                    "fields": {
                        "keyword": {
                            "type": "keyword",
                            "ignore_above": 256
                        },
                        "ngr": {
                            "type": "text",
                            "analyzer": "ngram_analyzer"
                        },
                        "stem": {
                            "type": "text",
                            "analyzer": "stem_analyzer"
                        }
                    }
                },
                "libel_clean": {
                    "type": "text",
                    "fields": {
                        "keyword": {
                            "type": "keyword",
                            "ignore_above": 256
                        },
                        "ngr": {
                            "type": "text",
                            "analyzer": "ngram_analyzer"
                        },
                        "stem": {
                            "type": "text",
                            "analyzer": "stem_analyzer"
                        }
                    }
                },
                "energy_100g": {
                    "type": "float",
                    "ignore_malformed": true
                },
                "nutriscore_score": {
                    "type": "float",
                    "ignore_malformed": true
                }
            }
        }
    }