::: {.content-visible when-profile="fr"}
# Récupérer des informations sur les pokemons

Le prochain exercice pour mettre en pratique le _web scraping_
consiste à récupérer des informations sur les
pokemons à partir du
site internet [pokemondb.net](http://pokemondb.net/pokedex/national).



## Version non guidée
:::

::: {.content-visible when-profile="en"}
# Retrieving Information on Pokémon

The next exercise to practice _web scraping_
involves retrieving information on Pokémon
from the website [pokemondb.net](http://pokemondb.net/pokedex/national).

## Unguided Version
:::


::: {.callout-important}
:::: {.content-visible when-profile="fr"}
Comme pour Wikipedia, ce site demande à `request` d'indiquer un paramètre pour contrôler l'_user-agent_. Par exemple, 
::::
:::: {.content-visible when-profile="en"}
As with Wikipedia, this site asks `request` to specify a parameter to control the _user-agent_. For instance,
::::

```{.python}
requests.get(... , headers = {'User-Agent': 'Mozilla/5.0'})
```
:::


{{< include "04_webscraping/_exo2.qmd" >}}


::: {.content-visible when-profile="fr"}
Pour la question 1, l'objectif est d'obtenir le code source d'un tableau comme celui qui suit (Pokémon [Nincada](http://pokemondb.net/pokedex/nincada)).
:::

::: {.content-visible when-profile="en"}
For question 1, the goal is to obtain the source code of a table like
the one below (Pokémon [Nincada](http://pokemondb.net/pokedex/nincada)).
:::

::: {.cell .markdown}
<div class="grid-col span-md-6 span-lg-4">
<h2>Pokédex data</h2>
<table class="vitals-table">
<tbody>
<tr>
<th>National №</th>
<td><strong>290</strong></td>
</tr>
<tr>
<th>Type</th>
<td>
<a class="type-icon type-bug" href="/type/bug">Bug</a> <a class="type-icon type-ground" href="/type/ground">Ground</a> </td>
</tr>
<tr>
<th>Species</th>
<td>Trainee Pokémon</td>
</tr>
<tr>
<th>Height</th>
<td>0.5&nbsp;m (1′08″)</td>
</tr>
<tr>
<th>Weight</th>
<td>5.5&nbsp;kg (12.1&nbsp;lbs)</td>
</tr>
<tr>
<th>Abilities</th>
<td><span class="text-muted">1. <a href="/ability/compound-eyes" title="The Pokémon's accuracy is boosted.">Compound Eyes</a></span><br><small class="text-muted"><a href="/ability/run-away" title="Enables a sure getaway from wild Pokémon.">Run Away</a> (hidden ability)</small><br></td>
</tr>
<tr>
<th>Local №</th>
<td>042 <small class="text-muted">(Ruby/Sapphire/Emerald)</small><br>111 <small class="text-muted">(X/Y — Central Kalos)</small><br>043 <small class="text-muted">(Omega Ruby/Alpha Sapphire)</small><br>104 <small class="text-muted">(Sword/Shield)</small><br></td>
</tr>
</tbody>
</table>
</div>


<div class="grid-col span-md-12 span-lg-4">
<div class="grid-row">
<div class="grid-col span-md-6 span-lg-12">
<h2>Training</h2>
<table class="vitals-table">
<tbody>
<tr>
<th>EV yield</th>
<td class="text">
1 Defense </td>
</tr>
<tr>
<th>Catch rate</th>
<td>255 <small class="text-muted">(33.3% with PokéBall, full HP)</small></td>
</tr>
<tr>
<th>Base <a href="/glossary#def-friendship">Friendship</a></th>
<td>70 <small class="text-muted">(normal)</small></td>
</tr>
<tr>
<th>Base Exp.</th>
<td>53</td>
</tr>
<tr>
<th>Growth Rate</th>
<td>Erratic</td>
</tr>
</tbody>
</table>
</div>
<div class="grid-col span-md-6 span-lg-12">
<h2>Breeding</h2>
<table class="vitals-table">
<tbody>
<tr>
<th>Egg Groups</th>
<td>
<a href="/egg-group/bug">Bug</a> </td>
</tr>
<tr>
<th>Gender</th>
<td><span class="text-blue">50% male</span>, <span class="text-pink">50% female</span></td> </tr>
<tr>
<th><a href="/glossary#def-eggcycle">Egg cycles</a></th>
<td>15 <small class="text-muted">(3,599–3,855 steps)</small>
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>

<div class="grid-col span-md-12 span-lg-8">
<div id="dex-stats"></div>
<h2>Base stats</h2>
<div class="resp-scroll">
<table class="vitals-table">
<tbody>
<tr>
<th>HP</th>
<td class="cell-num">31</td>
<td class="cell-barchart">
<div style="width:17.22%;" class="barchart-bar barchart-rank-2 "></div>
</td>
<td class="cell-num">172</td>
<td class="cell-num">266</td>
</tr>
<tr>
<th>Attack</th>
<td class="cell-num">45</td>
<td class="cell-barchart">
<div style="width:25.00%;" class="barchart-bar barchart-rank-2 "></div>
</td>
<td class="cell-num">85</td>
<td class="cell-num">207</td>
</tr>
<tr>
<th>Defense</th>
<td class="cell-num">90</td>
<td class="cell-barchart">
<div style="width:50.00%;" class="barchart-bar barchart-rank-4 "></div>
</td>
<td class="cell-num">166</td>
<td class="cell-num">306</td>
</tr>
<tr>
<th>Sp. Atk</th>
<td class="cell-num">30</td>
<td class="cell-barchart">
<div style="width:16.67%;" class="barchart-bar barchart-rank-2 "></div>
</td>
<td class="cell-num">58</td>
<td class="cell-num">174</td>
</tr>
<tr>
<th>Sp. Def</th>
<td class="cell-num">30</td>
<td class="cell-barchart">
<div style="width:16.67%;" class="barchart-bar barchart-rank-2 "></div>
</td>
<td class="cell-num">58</td>
<td class="cell-num">174</td>
</tr>
<tr>
<th>Speed</th>
<td class="cell-num">40</td>
<td class="cell-barchart">
<div style="width:22.22%;" class="barchart-bar barchart-rank-2 "></div>
</td>
<td class="cell-num">76</td>
<td class="cell-num">196</td>
</tr>
</tbody>
<tfoot>
<tr>
<th>Total</th>
<td class="cell-total"><b>266</b></td>
<th class="cell-barchart"></th>
<th>Min</th>
<th>Max</th>
</tr>
</tfoot>
</table>
</div>
</div>
:::

::: {.content-visible when-profile="fr"}
Pour la question 2, l'objectif est d'obtenir
les images des pokémons comme dans la @fig
:::

::: {.content-visible when-profile="en"}
For question 2, the goal is to obtain
images of the Pokémon.
:::



::: {.content-visible when-profile="fr"}
## Version guidée

Les prochaines parties permettront de faire l'exercice ci-dessus
étape par étape,
de manière guidée.

Nous souhaitons tout d'abord obtenir les
informations personnelles de tous
les pokemons sur [pokemondb.net](http://pokemondb.net/pokedex/national).

Les informations que nous aimerions obtenir au final pour les pokemons sont celles contenues dans 4 tableaux :

- Pokédex data
- Training
- Breeding
- Base stats

Nous proposons ensuite de récupérer et afficher les images.

### Etape 1: constituer un DataFrame de caractéristiques
:::

::: {.content-visible when-profile="en"}
## Guided Version

The following sections will help you complete the above exercise
step by step,
in a guided manner.

First, we want to obtain the
personal information of all
the Pokémon on [pokemondb.net](http://pokemondb.net/pokedex/national).

The information we would like to ultimately obtain for the Pokémon is contained in 4 tables:

- Pokédex data
- Training
- Breeding
- Base stats

Next, we will retrieve and display the images.

### Step 1: Create a DataFrame of Characteristics
:::



{{< include "04_webscraping/_exo2b.qmd" >}}
{{< include "04_webscraping/_exo2_solution.qmd" >}}


::: {.content-visible when-profile="fr"}
### Etape 2: récupérer et afficher des photos de Pokémon

Nous aimerions que vous récupériez également les images des 5 premiers pokémons
et que vous les enregistriez dans un dossier.
:::

::: {.content-visible when-profile="en"}
### Step 2: Retrieve and Display Pokémon Photos

We would also like you to retrieve the images of the first 5 Pokémon
and save them in a folder.
:::


{{< include "04_webscraping/_exo2b_suite.qmd" >}}
{{< include "04_webscraping/_exo2b_correction.qmd" >}}
