::: {.content-visible when-profile="fr"}
:::: {.exercise} 
## Exercice 2 : Les pokémon (version non guidée)

Pour cet exercice, nous vous demandons d'obtenir différentes informations sur les pokémons :

1. les informations personnelles des __893__ pokemons sur le site internet [pokemondb.net](http://pokemondb.net/pokedex/national).
   Les informations que nous aimerions obtenir au final dans un `DataFrame` sont celles contenues dans 4 tableaux :

   - Pokédex data
   - Training
   - Breeding
   - Base stats

2. Nous aimerions que vous récupériez également les images de chacun des pokémons et que vous les enregistriez dans un dossier.

* Petit indice : utilisez les modules `request` et [`shutil`](https://docs.python.org/3/library/shutil.html)
* Pour cette question, il faut que vous cherchiez de vous même certains éléments, tout n'est pas présent dans le TD.

::::
:::

::: {.content-visible when-profile="en"}
:::: {.exercise} 
## Exercise 2: Pokémon (Unguided Version)

For this exercise, we ask you to obtain various information about Pokémon:

1. The personal information of the __893__ Pokémon on the website [pokemondb.net](http://pokemondb.net/pokedex/national).
   The information we would like to ultimately obtain in a `DataFrame` is contained in 4 tables:

   - Pokédex data
   - Training
   - Breeding
   - Base stats

2. We would also like you to retrieve images of each Pokémon and save them in a folder.

* A small hint: use the `request` and [`shutil`](https://docs.python.org/3/library/shutil.html) modules.
* For this question, you will need to research some elements on your own; not everything is covered in the lab.

::::
:::
