::: {.content-visible when-profile="fr"}
:::: {.callout-tip}
## Exercice 2b : Les pokémons (version guidée)

Pour récupérer les informations, le code devra être divisé en plusieurs étapes : 


1. Trouvez la page principale du site et la transformer en un objet intelligible pour votre code. Les fonctions suivantes vous seront utiles :

   - `requests.get`
   - `bs4.BeautifulSoup`

2. A partir de ce code, créer une fonction qui permet de récupérer le copntenu page d'un pokémon à partir de son nom. Vous pouvez nommer cette fonction `get_name`.

3. À partir de la page de `bulbasaur`, obtenez les 4 tableaux qui nous intéressent :

   - on va chercher l'élément suivant : `('table', { 'class' : "vitals-table"})`
   - puis stocker ses éléments dans un dictionnaire

4. Récupérez par ailleurs la liste de noms des pokémons qui nous permettra de faire une boucle par la suite. Combien trouvez-vous de pokémons ? 

5. Écrivez une fonction qui récupère l'ensemble des informations sur les dix premiers pokémons de la liste et les intègre dans un `DataFrame`.

::::
:::

::: {.content-visible when-profile="en"}
:::: {.callout-tip}
## Exercise 2b: Pokémon (guided version)

To retrieve the information, the code must be divided into several steps: 

1. Find the site's main page and transform it into an intelligible object for your code. The following functions will be useful:

   - `requests.get`
   - `bs4.BeautifulSoup`

2. From this code, create a function that retrieves a pokémon's page content from its name. You can name this function `get_name`.

3. From the `bulbasaur` page, obtain the 4 arrays we're interested in:
   - look for the following element: `(‘table’, { ‘class’ : “vitals-table”})`
   - then store its elements in a dictionary

4. Retrieve the list of pokemon names, which will enable us to loop later. How many pokémons can you find? 

5. Write a function that retrieves all the information on the first ten pokémons in the list and integrates it into a `DataFrame`.

::::
:::

```{python}
# Correction above
```