---
title: "Webscraping avec python"
date: 2020-09-08T13:00:00Z
draft: false
weight: 60
slug: webscraping
tags:
  - Deep Learning
  - DallE
  - Tutoriel
  - Image
  - Thèmes avancés
categories:
  - Tutoriel
  - Avancé
type: book
summary: |
  La _hype_ autour du
  modèle de génération d'image `Dall-E` a amené 
  une grande attention sur les modèles
  autogénératifs de contenu. `Dall-E` est, à l'heure
  actuelle, le modèle le plus célèbre de génération
  d'image à partir de texte. Il est maintenant
  possible de créer, depuis `Python` grâce à 
  l'implémentation de [`StableDiffusion`](https://huggingface.co/CompVis/stable-diffusion-v1-4),
  soit-même
  ses propres images rigolotes.
---

Pour tester les exemples présentés dans ce chapitre:

::: {.cell .markdown}
```{python}
#| echo: false
#| output: 'asis'
#| include: true
#| eval: true

import sys
sys.path.insert(1, '../../../../') #insert the utils module
from utils import print_badges

#print_badges(__file__)
print_badges("content/course/modern-ds/dallE.qmd")
```
:::

{{% box status="note" title="Remarque" icon="fa fa-lightbulb" %}}
L'utilisation de ce tutoriel est assez exigeante en termes d'infrastructure
car il est nécessaire de disposer de GPU.

Bien qu'il en existe sur
le _cloud_ du SSPCloud, je n'ai pas encore eu le temps de creuser la configuration
à mettre en oeuvre pour répliquer ce chapitre.

Pour le moment, il faudra
se contenter de `Google Colab` pour tester ces exemples. La configuration
à mettre en oeuvre pour tester ces exemples est présentée dans une autre
boîte. 
{{% /box %}}

{{% box status="note" title="Utiliser des GPU sur `Colab`" icon="fa fa-lightbulb" %}}
Par défaut, Colab n'utilise pas de GPU mais de la CPU. Il est donc nécessaire
d'éditer les paramètres d'exécution du Notebook
- Dans le menu `Exécution`, cliquer sur `Modifier le type d'exécution`
- Sélectionner `GPU` sous `Accélérateur matériel`
{{% /box %}}
