:::: {.content-visible when-profile="fr"}

::: {.exercise}
## Exercice 2 : n-grams et contexte du mot fear

1. Utiliser la méthode `concordance` pour afficher le contexte dans lequel apparaît le terme `fear`.
2. Sélectionner et afficher les meilleures collocations, par exemple selon le critère du ratio de vraisemblance.

Lorsque deux mots sont fortement associés, cela est parfois dû au fait qu'ils apparaissent rarement. Il est donc parfois nécessaire d'appliquer des filtres, par exemple ignorer les bigrammes qui apparaissent moins de 5 fois dans le corpus.

3. Refaire la question précédente en utilisant toujours un modèle `BigramCollocationFinder` suivi de la méthode `apply_freq_filter` pour ne conserver que les bigrammes présents au moins 5 fois. Puis, au lieu d'utiliser la méthode de maximum de vraisemblance, testez la méthode `nltk.collocations.BigramAssocMeasures().jaccard`.

4. Ne s'intéresser qu'aux *collocations* qui concernent le mot *fear*

:::

::::

:::: {.content-visible when-profile="en"}

::: {.exercise}
## Exercise 2: n-grams and the Context of the Word "fear"

1. Use the `concordance` method to display the context in which the word `fear` appears.
2. Select and display the top collocations, for instance using the likelihood ratio criterion.

When two words are strongly associated, it may be due to their rarity. Therefore, it's often necessary to apply filters—for example, ignore bigrams that occur fewer than 5 times in the corpus.

3. Repeat the previous task using the `BigramCollocationFinder` model, followed by the `apply_freq_filter` method to retain only bigrams appearing at least 5 times. Then, instead of the likelihood ratio, test the method `nltk.collocations.BigramAssocMeasures().jaccard`.

4. Focus only on *collocations* involving the word *fear*.

:::

::::

