:::: {.content-visible when-profile="fr"}

::: {.exercise}
## Exercice 5: barplot des comptages mensuels

1. Créer une variable `month` dont le format respecte, par exemple, le schéma `2019-08` grâce à la bonne option de la méthode `dt.to_period`

2. Appliquer les conseils précédents pour construire et améliorer graduellement un graphique afin d'obtenir une figure similaire à la 3e production sur la page de l'_open data_ parisien. Faire cette figure d'abord depuis début 2022 puis sur toute la période de notre historique 

3. Question optionnelle: représenter la même information sous forme de _lollipop_

:::

::::

:::: {.content-visible when-profile="en"}

::: {.exercise}
## Exercise 5: Monthly Counts Barplot

1. Create a `month` variable whose format follows, for example, the `2019-08` scheme using the correct option of the `dt.to_period` method.

2. Apply the previous tips to gradually build and improve a graph to obtain a figure similar to the 3rd production on the Parisian _open data_ page. Create this figure first from early 2022 and then over the entire period of our history.

3. Optional Question: Represent the same information in the form of a _lollipop_.

:::

::::
