:::: {.content-visible when-profile="fr"}
::: {.exercise}
## Exercice 1 : Produire un premier graphique

Les données comportent plusieurs dimensions pouvant faire l'objet d'une analyse statistique. Nous allons commencer par nous focaliser sur le volume de passage à tel ou tel compteur.

Puisque nous avons comme objectif de synthétiser l'information présente dans notre jeu de données, nous devons d'abord mettre en œuvre quelques agrégations _ad hoc_ pour produire un graphique lisible.

1. Garder les dix bornes à la moyenne la plus élevée. Comme pour obtenir un graphique ordonné du plus grand au plus petit avec les méthodes `plot` de `Pandas`, il faut avoir les données ordonnées du plus petit au plus grand (oui c'est bizarre mais c'est comme ça...), réordonner les données.

2. En premier lieu, sans se préoccuper des éléments de style ni de la beauté
du graphique, créer la structure du _barplot_ (diagramme en bâtons) de la
[page d'analyse des données](https://opendata.paris.fr/explore/dataset/comptage-velo-donnees-compteurs/dataviz/?disjunctive.id_compteur&disjunctive.nom_compteur&disjunctive.id&disjunctive.name).

3. Pour préparer le travail sur la deuxième figure, ne conserver
que les 10 compteurs ayant comptabilisé le plus de vélos.

4. Comme pour la question 2, créer un _barplot_
pour reproduire la figure 2 de l'_open data_ parisien.

:::
::::

:::: {.content-visible when-profile="en"}
::: {.exercise}
## Exercise 1: Create an Initial Plot

The data includes several dimensions that can be analyzed statistically. We'll start by focusing on the volume of passage at various counting stations.

Since our goal is to summarize the information in our dataset, we first need to perform some _ad hoc_ aggregations to create a readable plot.

1. Retain the ten stations with the highest average. To get an ordered plot from largest to smallest using `Pandas` plot methods, the data must be sorted from smallest to largest (yes, it's odd but that's how it works...). Sort the data accordingly.

2. Initially, without worrying about styling or aesthetics, create the structure of a _barplot_ (bar chart) as seen on the
[data analysis page](https://opendata.paris.fr/explore/dataset/comptage-velo-donnees-compteurs/dataviz/?disjunctive.id_compteur&disjunctive.nom_compteur&disjunctive.id&disjunctive.name).

3. To prepare for the second figure, retain only the 10 stations that recorded the highest total number of bicycles.

4. As in question 2, create a _barplot_ to replicate figure 2 from the Paris open data portal.

:::
::::
