```{python}
#| label: exo1-df1
df1 = (
    df
    .groupby('nom_compteur')
    .agg({'sum_counts': "mean"})
    .sort_values('sum_counts', ascending = False)
    .head(10)
    .sort_values('sum_counts')
)
```

:::: {.content-visible when-profile="fr"}
Les 10 principales stations à l'issue de la question 1 représentent celles ayant la moyenne la plus élevée pour le volume de passages de vélos. Ces données réordonnées permettent de créer un graphique lisible et de mettre en avant les stations les plus fréquentées.
::::

:::: {.content-visible when-profile="en"}
The top 10 stations from question 1 are those with the highest average bicycle traffic. These reordered data allow for creating a clear visualization highlighting the busiest stations.
::::

```{python}
df1.head()
```


```{python}
#| output: false

# Question 2
p1 = df1.plot(kind = "barh", color = 'red')
```

:::: {.content-visible when-profile="fr"}
La @fig-figure1-exo1-fr présente les données sous forme de _barplot_ basique. Bien qu'elle montre les informations essentielles, elle manque de mise en page esthétique, de couleurs harmonieuses et d'annotations claires, nécessaires pour améliorer la lisibilité et l'impact visuel.
::::

:::: {.content-visible when-profile="en"}
@fig-figure1-exo1-en, displays the data in a basic _barplot_. While it conveys the essential information, it lacks aesthetic layout, harmonious colors, and clear annotations, which are necessary to improve readability and visual impact.
::::


:::: {.cell .markdown}
<details open>

::: {.content-visible when-profile="fr"}

<summary>
Figure 1 (cliquer ici pour rétracter)
</summary>


```{python}
#| echo: false
#| fig-cap: "Première ébauche de la figure \"Les 10 compteurs avec la moyenne horaire la plus élevée\""
#| label: fig-figure1-exo1-fr
p1.figure
```

:::

::: {.content-visible when-profile="en"}

<summary>
Figure 1 (click here to mask)
</summary>


```{python}
#| echo: false
#| fig-cap: "First draft for 'The 10 meters with the highest hourly average'"
#| label: fig-figure1-exo1-en
p1.figure
```

:::


</details>
::::

```{python}
# Question 4
df2 = (
    df
    .groupby('nom_compteur')
    .agg({'sum_counts': "sum"})
    .sort_values('sum_counts', ascending = False)
    .head(10)
    .sort_values('sum_counts')
)
```

```{python}
#| output: false
# Question 5
p2 = df2.plot(kind = "barh", color = 'green')
```

::::: {.cell .markdown}

<details open>

:::: {.content-visible when-profile="fr"}

<summary>
Figure 2 sans travail sur le style (cliquer ici pour rétracter):
</summary>

```{python}
#| echo: false
#| fig-cap: "Première ébauche de la figure \"Les 10 compteurs ayant comptabilisés le plus de vélos\""
#| label: fig-figure2-exo1-fr
p2.figure
```

::::

:::: {.content-visible when-profile="en"}

<summary>
Figure 2 without styling (click here to mask):
</summary>

```{python}
#| echo: false
#| fig-cap: "First draft of the figure 'The 10 counters that recorded the most bicycles'"
#| label: fig-figure2-exo1-en
p2.figure
```

::::


</details>

:::::

