name: Deploy website to Netlify and build notebooks

on:
  push:
    branches:
      - main
      - master
      - autocorrection

jobs:
  blogdown:
    name: Render-Blog
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Install rmarkdown
        env:
          GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
        run: |
          Rscript -e 'install.packages(c("rmarkdown"))'
      - name: install hugo
        run: Rscript -e 'blogdown::install_hugo("0.83.0", force = TRUE)'
      - name: Install Python
        run: |
          Rscript -e 'print(blogdown:::hugo_version())'
          Rscript -e "install.packages(c('remotes', 'reticulate'))"
          Rscript -e "install.packages(c('here'))"
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Modif Rmd echo status
        run: |
         python build/modifmd.py
      - name: Render blog
        run: |
          Rscript -e 'source("./build/build.R")'
      - name: Clean files with Python function
        run: |
         rm -rf "./temp"
         mkdir -p temp
         mkdir -p notebooks
         python build/cleanmd.py
      - name: Convert in ipynb with Jupytext
        run: |
         pip install jupytext
         cd ./temp
         for i in $(find . -type f \( -iname "*.Rmd" \)); do \
            j="${i%.Rmd}.md" ;
            echo "$j" ;
            if [ -e $j ]
            then
              echo "Converting $j"; \
              #jupytext --to py --execute "$i"
              jupytext --to ipynb "$j" ;
              k="${j%.md}.ipynb" ;
            fi            
         done
         mkdir -p ../notebooks
         cp -R . ../notebooks
         cd ..
      - uses: actions/upload-artifact@v2
        with:
          name: Notebooks
          path: temp/
