name: Docker Build (Visual Studio)

on:
  push:
    branches:
      - main
      - master
      - docker

jobs:
  docker:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        if: ${{ github.repository == 'linogaliana/python-datascientist-docker' }}
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        if: ${{ github.repository == 'linogaliana/python-datascientist-docker' }}
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: ${{ github.repository == 'linogaliana/python-datascientist-docker' }}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        if: ${{ github.repository == 'linogaliana/python-datascientist-docker' }}
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        with:
          file: "docker/Dockerfile"
          push: true
          tags: linogaliana/python-datascientist:dev
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}